### ISSUE TITLE
SQL logging during seeding

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#1011]
### Discussed in https://github.com/loco-rs/loco/discussions/959

<div type='discussions-op-text'>

<sup>Originally posted by **felipesere** November  3, 2024</sup>
Not sure if I'm holding it wrong 🤷‍♂️

I'm trying to move my PostsgreSQL backed app to use Sqlite (for "reasons") and my current hurdle is that I get the following error when seeding the users:
```
called `Result::unwrap()` on an `Err` value: DB(Json("premature end of input"))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Is there a way to turn on SQL logging for seeding? I have it turned on in my test config but I see nothing.
It's hard to tell which column gives me grief :) </div>

**Comment by felipesere** [comment]
I’m on my phone so can’t check this. But given that migrations are a separate crate with its own Cargo.toml, il pretty sure we would have to turn on the logging feature in the SeaORM dependency there… 

I haven’t checked if it can be turned on at the crate level and then turned back off at runtime to be able to control it from the loco config.

**Comment by jondot** [comment]
no worries, i'll take a look as well

**Comment by jondot** [comment]
I did some checking, looks like logging and its flag wiring is good. Migration crate will get an already-initialized connection from the main Loco set up, so it will share what ever configuration were given initially.

I'm wondering if configuration on your end is really in sync with what you're running. For example, if you're running tests and expect to see these logs - your `test.yaml` might contain different flags, and also `test.yaml` has different log levels. I'd start with `development.yaml` for this.

The error itself follows from Sqlite requiring a `Z` to parse properly, indeed.

**Comment by jondot** [comment]
closing for now, please reopen if needed

**Comment by Isaac-Leonard** [comment]
I'm not sure if this has been fixed since this issue was made, I'm using an older version of loco at the moment so it very much may have been however I'm getting the same error as reported in the issue.
I can fix it easily enough by adding a Z to the end of date-time strings in the yaml file however my issue is that I generated the yaml file by runing cargo run db seed --dump and then tried to run cargo run db seed --reset, which gave me the issue meaning the date-times don't deserialise properly from their serialised format and have to manually be fixed.
Again feel free to ignore this if this has already been fixed in the last year.

**Comment by askor** [comment]
@Isaac-Leonard I made and issue for this.

Can you tell me how exactly you edited the fixture (by adding Z) to make it work?

Here is an example broken fixture:

```
- pid: a24f7f05-93b2-4b8b-b861-dcc564de8327
  created_at: 2026-01-31 19:31:49
  id: 1
  password: $argon2id$v=19$m=19456,t=2,p=1$bElaPnqNDmqgr3OQce0d2Q$8u5QFQxfh5Ygh9SrgFez59UUcianRij0Ie9UxZwJsnU
  name: Jane Doe
  email: jane.doe@example.com
  updated_at: 2026-01-31 19:31:49
  email_verification_token: dd898234-cbf6-4a36-a229-355f0ce76dad
  email_verification_sent_at: 2026-01-31T20:31:49.849469+01:00
  api_key: lo-62300bd7-9f7a-4085-8f9c-81e68ab11066
```
