### ISSUE TITLE
Duplication in docs

### ISSUE THREAD

**Issue by thesurlydev** [loco-rs/loco#105]
**Description**

There's some duplication in the documentation:

```
token - which is a JWT token which allow to create a requests to auth endpoints. in the [config](https://loco.rs/docs/getting-started/config/) you can change the default token expiration and make sure that secret is different between the environments.

pid - generated id when creating a new user.

name - the user name.

is_verified - Is a flag if the user verify his account or not.

Token: A JWT token enabling requests to authentication endpoints. Refer to the [configuration documentation](https://loco.rs/docs/getting-started/config/) to customize the default token expiration and ensure that the secret differs between environments.

pid - A unique identifier generated when creating a new user.

Name - The user's name associated with the account.

Is Verified - A flag indicating whether the user has verified their account.
```

**To Reproduce**

Found here: https://loco.rs/docs/features/authentication/

**Expected Behavior**

**Environment:**

**Additional Context**

Include additional context about the issue in this section. For instance, share insights into the bug's discovery process or any hypotInclude additional context about the issue in this section. For instance, share insights into the bug's discovery process or any hypotheses you may have regarding the root cause or specific aspects where Loco may be malfunctioning.

**Comment by kaplanelad** [comment]
Thanks @thesurlydev i have [removed](https://github.com/loco-rs/loco/commit/b8d8803a8b1d5029f3233d92d6a499c922eebcc7) the duplication and going to update the site soon
