### ISSUE TITLE
Remove OpenSSL Requirement

### ISSUE THREAD

**Issue by mccormickt** [loco-rs/loco#1056]
**Description**

The addition of the `reqwest` dependency in #1000  brings in `openssl` / `openssl-sys` dependencies with its default features. It would be great if we could modify this dependency to disable default features, utilize the `rusttls-tls` feature instead of `default-tls`, and enable the other required default features. 

**To Reproduce**

Please outline the steps to replicate the bug, and if possible, provide a comprehensive code example consisting of both `main.rs` and `Cargo.toml` files. A complete and functional code snippet would be highly appreciated.

**Expected Behavior**

No dependencies on the host's openssl installation. 

**Environment:**

**Additional Context**

Building loco into minimal container images or the like works best with just `rustls` and not having to install openssl. 

Also, `cargo-deny`'s `deny.toml` could be used in the future to explicitly audit for `openssl` dependencies. 
 `deny = [{ name = "openssl" }, { name = "openssl-sys" }]`

**Comment by jondot** [comment]
thanks! yes, happy to accept a PR for this
