### ISSUE TITLE
Add a `rails db:create` equivalent

### ISSUE THREAD

**Issue by mateusdeap** [loco-rs/loco#112]
## Feature Request

**Is your feature request related to a problem? Please describe.**

It is not. Well, it just makes the job of creating the application's database easier, but as discussed in #102, this doesn't seem to be common practice among frameworks but rather something unique to Rails and Phoenix. So it's not a problem because there are many ways to achieve this without a framework included command. But it is because we all like that easy setup experience right?

**Describe the solution you'd like**

I'm new to Rust and loco, so I'm just going to write this as if it were like in Rails.

I'd like to be able to create my app, set my preferred db, username and password and just run:

```
loco db:create
```

And I would have my database.

**Describe alternatives you've considered**

The alternative seems to do things separately, as many frameworks do. As for different implementations, given my inexperience with Rust, can't say I've made much headway in that regard, but I do want to learn, so I'm willing to help out any way I can.

**Comment by jondot** [comment]
Looks good. @mateusdeap  is this something you'd like to try and implement?

**Comment by mateusdeap** [comment]
Fine by me although I think I'd need some guidance and some time to figure things out. Since we do have other tasks in loco, like `new`, any place in the codebase I should look for reference? Any docs on how these commands are written?

**Comment by jondot** [comment]
Cool, let's try step by step.
### Setting up a dev env

1. Clone the project, and try your first `cargo test` in the root of the project
2. Next, cd examples/demo. This is a "driver app" we use to test out new features, it directly references the local framework (`../../`)
3. in `examples/demo` try your first `cargo test`. if it fails, make sure you have:
Redis running (can be a local redis or Docker based)
Postgres running (can be local or Docker based)
Open `config/test.yaml` and look for the connection strings, see that you're good
4. Once you have a passing test, you're ready to go.

### Adding the `db:create` feature: the wiring

1. The work you'll do will probably end up here: https://github.com/loco-rs/loco/blob/master/src/db.rs
2. Now we want to (1) expose a new command (2) add the logic in `db.rs`
3. Exposing a new command would be done here: https://github.com/loco-rs/loco/blob/master/src/cli.rs#L153 (make sure to also update other enums referencing this enum)
4. Running a command: https://github.com/loco-rs/loco/blob/master/src/boot.rs#L193

### Adding an actual logic to create a database

1. This is how its done in rails: https://github.com/rails/rails/blob/main/activerecord/lib/active_record/connection_adapters/postgresql/schema_statements.rb#L22 so basically composing a DDL SQL statement and finding a connection to run it -- is all we need
2. You get a connection in almost every function, you can copy this: https://github.com/loco-rs/loco/blob/master/src/db.rs#L85
3. To execute raw sql, start here: https://www.sea-ql.org/SeaORM/docs/next/basic-crud/raw-sql/#execute-unprepared-sql-statement

Notes:
* We support postgres and sqlite. For sqlite there's no need to createdb.
* How do you know you're in Postgres? you can match on DatabaseConnection and look for the `SqlxPostgresPoolConnection` variant

**Comment by mateusdeap** [comment]
Thanks! Will give it a shot as soon as I can

**Comment by mateusdeap** [comment]
@jondot Sorry for letting this hang. I got really busy with end of year activities and such that I just didn't have enough free time to work on this despite me saying so.

@kaplanelad Thanks a lot for the PR and the feature!
