### ISSUE TITLE
Cloudflare Workers

### ISSUE THREAD

**Issue by ashermyers** [loco-rs/loco#123]
## Feature Request

[Cloudflare Workers](https://workers.cloudflare.com/) support would be amazing... [It seems to be already compatible with rust.](https://blog.cloudflare.com/workers-rust-sdk/)

**Comment by kaplanelad** [comment]
Hello @ashermyers,

I appreciate your suggestion! We're actively developing a deployment generator to streamline the project deployment process for various cloud environments.

To provide a quick overview, we've implemented a Docker solution. To view it, simply use the following command:
```sh
cargo loco generate deployment
```

in the incoming day, we are going to release a shuttle deployment. 

it would be amazing if you could open us a PR with  a generator for Cloudflare

**Comment by jondot** [comment]
Closing as we now have `generate deployment`

**Comment by magick93** [comment]
Does `generate deployment` support cloudflare workers?

**Comment by AnthonyMichaelTDM** [comment]
no

**Comment by iamrahulroy** [comment]
> Does generate deployment support cloudflare workers?
If it doesn't support Cloudflare workers, then what would it take to support it?

I've never touched Rust, but coming from Rails background I would love to start exploring loco with Cloudflare workers. @jondot would be nice to hear more from you. Thanks!
