### ISSUE TITLE
loco-rs@0.1.6 does not follow semver

### ISSUE THREAD

**Issue by pksunkara** [loco-rs/loco#128]
**Description**

loco-rs@0.1.6 is a minor release but it has major changes which are breaking. More details at https://changelog.fyi/deps/cargo/loco-rs/versions/0.1.6

**Additional Context**

Feel free to ignore if you don't plan to follow semver or plan to wait for a more stable release, but I wanted to let you know just in case.

**Comment by jondot** [comment]
Closing this for cleanups
