### ISSUE TITLE
generate code request_test template error

### ISSUE THREAD

**Issue by fan-tastic-z** [loco-rs/loco#132]
When executing `cargo loco generate scaffold post title:string content:text` of https://loco.rs/docs/getting-started/tour/#adding-a-crud-api, the generated code is in `tests/requests/post.rs` now code is `use blo::app::App` This should be `use {{pkg_name}}::app::App;` 
<img width="1280" alt="image" src="https://github.com/loco-rs/loco/assets/142720801/1e38cfa9-12bd-4f9c-bc5a-7a1890de7aa5">

**Comment by fan-tastic-z** [comment]
Can I submit a PR to fix it?

**Comment by jondot** [comment]
Yes, we'd love your help, thanks!
