### ISSUE TITLE
Modules based on convention, eliminating many `mod.rs` files.

### ISSUE THREAD

**Issue by kolektiv** [loco-rs/loco#135]
**Description**

I saw [your reply](https://www.reddit.com/r/rust/comments/18aokzc/comment/kc250fs) to a comment on the original Reddit announcement where it was suggested to reduce manual `mod.rs` work using a build script. As a suggestion, you could eliminate `mod.rs` entirely for some areas which are entirely based on convention anyway. So take `/controllers` as an example, you'll always want every file in there to be a public module. Rather than having to update the `mod.rs` every time, you could use something like [automod](https://crates.io/crates/automod) to do it by convention. Rather than having `pub mod controllers;` in your `lib.rs` and a `mod.rs` which needs maintaining in `/controllers`, you could have `pub mod controllers { automod::dir!(pub "/src/controllers"); }` - now every file added to `/controllers` will be a public module under `crate::controllers`. The same probably applies for most of the other directories that are convention-based, and where you need a little more control, such as `_entities` in models, you can still do that with this approach.

It has the advantage that any incremental code generation (new controllers/models/views from a scaffold command for example) no longer need to worry about updating any `mod.rs` files or anything - they'll just work straight away.

**To Reproduce**

I've not tried to reproduce anything, this is merely a suggestion on a potential way of eliminating a lot of boilerplate module code! It's actually not something I'd normally recommend for most things (explicit not magic is generally the Rust Way) but I think having a Rails-like conventions approach is actually one reasonable justification for breaking that rule occasionally. Anything surprising will still get picked up by the compiler as well, so it's magic with compile-time side-effects, not runtime!

<snip the rest of the template... />

**Comment by jondot** [comment]
Thanks, this is very cool, i wasnt aware of automod!

**Comment by kolektiv** [comment]
Yeah, it's not something that gets used a lot, I think, because it is a bit more "magic" than generally happens in Rust code (and I think the examples of usage given are about automatically including test files rather than production code). But I do believe that kind of approach has a place - for me, what Loco seems to be aiming for is a little outside of the usual Rust ethos - i.e. a little magic where it's useful but always with the ability to drop down to the nuts and bolts when wanted.

(And I found it myself ages ago purely by chance, looking through all the repos for @dtolnay - wow, that guy writes a lot of code; you can find something new you didn't realise you needed every time! Look at distributed slices somewhere for something else that might be useful to you, given the kind of things you're trying.)

**Comment by jondot** [comment]
Yes, @dtolnay stuff is solid. Which is why I think this is a great idea. We'll set up an experiment and see how it feels!

**Comment by jondot** [comment]
See https://github.com/loco-rs/loco/pull/150
