### ISSUE TITLE
can't use loco-cli to quick start a project which throw some error

### ISSUE THREAD

**Issue by eddiearc** [loco-rs/loco#137]
**Description**
enter the command:
$ loco new
$ ✔ ❯ App name? · xxx

will get those responses
$ 🙀 SecureTransport error: (null); class=Net (12)
$ 🙀 unexpected EOF; class=Http (34)
$ 🙀 failed to connect to github.com: Operation timed out; class=Os (2)

**To Reproduce**
maybe only in my compute?

**Expected Behavior**
normal create a project

**Environment:**
only use net proxy to access github

**Additional Context**
it maybe related to the internet env?

**Comment by kaplanelad** [comment]
Hey @eddiearc, 

thanks for reporting this issue. i'll check it. 
Loco cli calling in http to the repository for cloning the starter selection. do you have some network configuration to github?

**Comment by eddiearc** [comment]
> Hey @eddiearc,
> 
> thanks for reporting this issue. i'll check it. Loco cli calling in http to the repository for cloning the starter selection. do you have some network configuration to github?

thanks, it ready to run, just retry a few times, maybe because of my internet env...
