### ISSUE TITLE
Role based Authorization

### ISSUE THREAD

**Issue by brahimABD98** [loco-rs/loco#138]
Hello I think it would be really useful to have some basic role based authorization to guard different routes 
since currently I don't know if it's possible to add my own  middlewares  and constantly checking for role in every routes is really tedious 
thank you

**Comment by jondot** [comment]
Thanks, maybe you can put here some snippets of how you're checking for roles? we can use that as a basis to model & build some generic RBAC

**Comment by kaplanelad** [comment]
@brahimABD98 About your question of custom middleware you can create any custom middleware that you want. we are compatible with axum.

What you need to do:
1. create a the middleware rs file in your project
2. The middleware content should be implement `axum::extract::FromRequestParts`. for example:
```rust
use axum::{
  extract::{FromRef, FromRequestParts},
  http::{request::Parts},
};
use async_trait::async_trait;
#[derive(Debug, Deserialize, Serialize)]
 pub struct CustomMiddleware {
    pub custom: bool,
 }
#[async_trait]
impl<S> FromRequestParts<S> for CustomMiddleware
where
    AppContext: FromRef<S>,
    S: Send + Sync,
  {
    type Rejection = Error;

    async fn from_request_parts(parts: &mut Parts, state: &S) -> Result<Self, Error> {
       
     // custom logic
    Ok(CustomMiddleware{custom: true})
    }
  }
```
3. once you setup the middleware you can set the middleware in your controller:
```rust
async fn endpoint(custom_middleware: CustomMiddleware, State(ctx): State<AppContext>) -> Result<Json<CurrentResponse>> {
  custom_middleware.custom
...
}
```


If my example is not clear for you you can follow the our [auth middleware](https://github.com/loco-rs/loco/blob/master/src/controller/middleware/auth.rs#L49) and how we use it SAAS starter.

**Comment by MatzHilven** [comment]
Since this is `Rust On Rails`, having a variant of the [CanCanCan](https://github.com/CanCanCommunity/cancancan) Gem would be a gamechanger for me. I've been looking for an implementation for actix web/axum/... for some time now, this would be a great feature in my opinion.

**Comment by brahimABD98** [comment]
@jondot I've used [axum-login ](https://crates.io/crates/axum-login) recently with [AuthzBackend trait](https://docs.rs/axum-login/latest/axum_login/trait.AuthzBackend.html) and I think we could make it like [this](https://github.com/maxcountryman/axum-login/blob/main/examples/permissions/src/users.rs)   you can provide a couple of permissions name and it should be enough and we can add  group permissions

**Comment by kaplanelad** [comment]
After investigation, it looks like we don't have the option to cover all the scenarios. 
for now, this is something that we are not going to implement in Loco and gives the option to the users decide how they want to manage the different access
