### ISSUE TITLE
Problem with git config use "ssh" instead of "https" - authentication required but no callback set

### ISSUE THREAD

**Issue by lucasgrvarela** [loco-rs/loco#139]
If I have "use github ssh instead of https", the loco cli doesn't work to start a new app.

```
$ loco new
✔ ❯ App name? · myapp
🙀 authentication required but no callback set; class=Ssh (23); code=Auth (-16)

$ cat ~/.gitconfig 
[url "ssh://git@github.com/"]
	insteadOf = https://github.com/
```

Commenting out or removing this [url "ssh"] block was enough to get "loco new" working again.
```
$ cat ~/.gitconfig 
#[url "ssh://git@github.com/"]
#	insteadOf = https://github.com/

$ loco new
✔ ❯ App name? · myapp
? ❯ What would you like to build? › 
❯ Saas app (with DB and user auth)
  Stateless service (minimal, no db)
  Stateless HTML (minimal, no db)

```

**Comment by jondot** [comment]
Interesting case. I bumped into this before using the `git2` library, we need to set up some ssh config.

@kaplanelad I now remember that this is a reason why in backpack I went for spawning a `git` binary. Or we can also ditch git and download a tarball from github

something like this https://github.com/rusty-ferris-club/backpack/blob/master/backpack/src/vendors.rs#L91

and we can use some caching (if we formulate the URL in a way to indicate a version) https://github.com/rusty-ferris-club/backpack/blob/master/backpack/src/fetch.rs#L48

**Comment by kaplanelad** [comment]
Sure, let me see how can i solve it

**Comment by jondot** [comment]
Fixed, thanks @kaplanelad

**Comment by kaplanelad** [comment]
@lucasgrvarela publid in version 0.2.1.

To ensure you're up-to-date, please upgrade your loco-cli using the command: `cargo install loco-cli`
Verify the update by checking the version: `loco --version` should return 0.2.1 to newer.

**Comment by lucasgrvarela** [comment]
The fix worked well, thank you :)
