### ISSUE TITLE
Scaffold generates broken code in some failure cases

### ISSUE THREAD

**Issue by BWStearns** [loco-rs/loco#143]
**Description**

`cargo loco generate scaffold logs file_name:string hash:string created_at:ts`

This will fail to generate the `model` and `_entities` files because `created_at` is already included (perhaps this could be documented), but the command will still generate controller and view which will be broken. There is some warnings displayed but they're not super intuitive without having already seen this bug.

**To Reproduce**

`cargo loco generate scaffold logs file_name:string hash:string created_at:ts`

**Expected Behavior**

The command either succeeds, or displays an error and doesn't make changes.

If a default column is specified by the user it could replace the column or it could just error (the latter might be more straightforward). I think either behavior would be fine. 

**Environment:**

MBP

**Additional Context**

I haven't had time to dig into the code generation too much but afaict scaffold only generates whole new files with the exception of `mod.rs` files so maybe it could keep the original `mod.rs` contents in memory and there could be an unwind action on failures that removes created files and reverts the `mod.rs`s

**Comment by jondot** [comment]
Indeed a special case! thanks for catching this!
I can think of two solutions:

1. check a field existence before adding (using the various injection tools we have)
2. keep a list of `created_at`, etc. that we don't allow from the CLI when it's generating models because we already attach these by default (I'm in favor of this one, all generators give you created/updated for free)

would you like to contribute a solution?

**Comment by BWStearns** [comment]
I’d be happy to but it might be a minute. I might be able to get a PR in
next week or this weekend if I get lucky.

**Comment by kaplanelad** [comment]
@BWStearns be aware that i already fix it

**Comment by BWStearns** [comment]
Cool!

**Comment by BWStearns** [comment]
@kaplanelad fixed it

**Comment by kaplanelad** [comment]
@BWStearns, no worries! Just wanted to mention that this pull request hasn't been merged yet. I'm waiting for the CI to pass.
