### ISSUE TITLE
VSCode devcontainer

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#149]
Build a devcontainer for working with Loco

**Comment by jondot** [comment]
refs
https://github.com/microsoft/vscode-remote-try-rust
https://github.com/microsoft/vscode-remote-try-node

**Comment by kaplanelad** [comment]
@jondot you see it integrate with `cargo loco deployment`? or in somewhere else?

**Comment by jondot** [comment]
I have no clue actually, never used a devcontainer :)

**Comment by kaplanelad** [comment]
I experimented with dev containers and successfully configured them.
**For SaaS starter:**  the setup involves installing sea-orm-cli and loco-cli. Additionally, PostgreSQL, Redis, and a mail server are connected to Docker Compose.
**For stateless/HTML:** a simple Docker Compose configuration is sufficient.
