### ISSUE TITLE
Starters: re-shape by purpose

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#152]
Aggregating all feedback + reviewing current starters, here's how the list should appear by usecase

* `saas-spa` - SaaS for Single Page Apps
Preconfigured for front end in `frontend/`, includes a fallback index, asset location awareness, asset middleware. Starts in dev mode, start JS bundler in dev mode, go to app URL in browser and everything is playing with everything.
* `saas-api` - SaaS API - Just the API for people who generate the API, put it in a folder, and then go generate their own frontend stack in a different folder or project
* `stateless-service` - Stateless service - no postgres or Redis, for people who would be building some kind of lightweight integration service (e.g. calling to OpenAI, AWS, etc.) or want to integrate their own database (e.g. Influx, etc.). No background jobs, no mailers, no models. Yes for tasks.

Note that we need this:
* `service` - a blank service with no user authentication, no models, includes database, etc.

But for now, to minimize the number of starters so it can be maintainable -- we will advise: "generate with authentication and then delete the files you dont need"

Open questions:

* Can we use "base starters" and then layer some more functionality on them? for example the difference between SaaS starter and SaaS starter + SPA is configuration and 1-2 files.

**Comment by kaplanelad** [comment]
Saas starter: https://github.com/loco-rs/loco/pull/176

**Comment by kaplanelad** [comment]
All pr's merge to https://github.com/loco-rs/loco/pull/183

Testing now all the flows
