### ISSUE TITLE
Scaffold controller params always use Option

### ISSUE THREAD

**Issue by DanielMSchmidt** [loco-rs/loco#158]
**Description**

When I use scaffold with a required field the scaffolded controller Params have the field value to Option which causes an error in the update method since the SeaOrm Set method expects e.g. a `String` instead of `Option<String>`.

This is being generated:

```rust
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Params {
    pub title: Option<String>,
}

impl Params {
    fn update(&self, item: &mut ActiveModel) {
        item.title = Set(self.title.clone()); // <-- Error thrown here
    }
}
```

**To Reproduce**

In a new loco app run

`cargo loco generate scaffold blog title:string!`

**Expected Behavior**

It compiles out of the box

**Environment:**

**Additional Context**

**Comment by jondot** [comment]
nice catch!

**Comment by jondot** [comment]
fixed
