### ISSUE TITLE
Example using references

### ISSUE THREAD

**Issue by DanielMSchmidt** [loco-rs/loco#159]
## Feature Request

I am currently struggling to understand the relationship between loco and SeaOrm while also learning SeaOrm which makes it hard for me to write the code required for one to one, belongs to, one to many and many to many relationships.

**Describe the solution you'd like**

 It would be really cool if Loco could generate the required code for me, but in the mean time a single example with all these kinds of relationships would help me understand what to do.

**Describe alternatives you've considered**

A guide / documentation page would be fine as well.

**Comment by fan-tastic-z** [comment]
In fact, I also encountered the same problem. I want to try to implement the previous small Django project with loco, but I am not particularly clear about the use of one-to-many and many-pair in loco.

**Comment by kaplanelad** [comment]
Hi @DanielMSchmidt and @fan-tastic-z, appreciate your feedback!

Our ORM management relies on Seaorm. Check out the documentation [here](https://www.sea-ql.org/SeaORM/docs/0.6.x/relation/many-to-many/).

However, I'm happy to create a step-by-step guide for you. Could you provide some key points you'd like to see covered in this documentation?

**Comment by fan-tastic-z** [comment]
Hello, when defining a relationship, should it be defined in the migration or in the entity? I am confused about this, because from the logic of using loco, the table should be defined in the migration and the entity code should be generated.

**Comment by jondot** [comment]
You guys are correct. We hope to cover the material in #148 
If you guys want some points to be covered specifically feel free to comment.
Regarding "ORM Workflow", it is migration-first (you build a migration, and run `cargo loco entities` to regenerate the base entities)

**Comment by fan-tastic-z** [comment]
ok, thanks

**Comment by jondot** [comment]
This is done and should be available as part of 0.1.8, preview here: https://github.com/loco-rs/loco/blob/master/docs-site/content/docs/the-app/migration.md

Thanks for providing the feedback that helped create the new addition and docs!
