### ISSUE TITLE
The Loco Guide Update / Scaffold references issue

### ISSUE THREAD

**Issue by ace3** [loco-rs/loco#162]
**Description**

The current The Loco Guide, on the [Adding a second model](https://loco.rs/docs/getting-started/guide/#adding-a-second-model) section, missing some explanation to make it work.

So it's maybe missing the documentation or the scaffold function missing the section to add the referenced id to the params.

**To Reproduce**

Follow the loco guide, then until the adding the second model section. Follow the step, until the curl ( adding the comment ), will return the `{"error":"Bad Request"}` , since the `article_id` is not added to the params struct.

**Expected Behavior**

Should be able to add the comment based on articles id.

**Additional Context**

On the guide, need to change the `src/controllers/comments.rs` on the Params struct and Params implementation `update` into this

```rust
pub struct Params {
    pub content: Option<String>,
    pub article_id: i32, // <- add this
}

impl Params {
    fn update(&self, item: &mut comments::ActiveModel) {
        item.content = Set(self.content.clone());
        item.article_id = Set(self.article_id.clone()); // <- add this
    }
}
```

**Comment by jondot** [comment]
You're correct!
Would you like to add a PR so that you can appear as a contributor?

The source file and section is here:

https://github.com/loco-rs/loco/blob/master/docs-site/content/docs/getting-started/guide.md#adding-a-second-model

**Comment by ace3** [comment]
okay, i will try to enhance the documentation by doing PR.
it's a experience for me also, to contribute.

**Comment by jondot** [comment]
Thanks, merged!
