### ISSUE TITLE
add optional compression middleware

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#174]
mountable on assets or mountable on all responses

use `CompressionLayer` and take settings from a new middleware settings entry

**Comment by mikosco4real** [comment]
@jondot , please can you guide me to solve this one? It is my first time to open source contribution but I am really excited about this project.

**Comment by kaplanelad** [comment]
Hey @mikosco4real 
We are using (tower_http)[https://docs.rs/tower-http/latest/tower_http/] and they have a compression layer. 
I think we can use it

**Comment by mikosco4real** [comment]
Thanks, I will have a look at this one

**Comment by mikosco4real** [comment]
@kaplanelad, is it possible to get mentorship with this one. It is a little difficult for me. I will like to gain a good understand of the code base.

**Comment by kaplanelad** [comment]
Hey @mikosco4real 
I noticed that there's already progress on #205. However, I'd be happy to assist you with other issues we have. Feel free to join our Discord channel for a discussion, or write a comment in some issue that you are interested in, and we can chat about it there. 

Looking forward to collaborating!

**Comment by mikosco4real** [comment]
Thanks, I can see how he solved it in #205

**Comment by mikosco4real** [comment]
How do I join the discord group?

**Comment by kaplanelad** [comment]
you can click on discord badge on top of readme file

**Comment by mikosco4real** [comment]
Thank you. I have joined.
