### ISSUE TITLE
Add a "powered by" header

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#181]
Powered by: loco.rs

Let users disable this middleware easily via configuration, by default turned on.

**Comment by mikosco4real** [comment]
@jondot I would like to start contributing to this project, This would be my first open source contribution if I take on this one. I am really excited to start my journey to open source. And loco-rs is already helping me to quickly develop my side project. Coming from Django(python) this is just the project I have been looking for in Rust. I want to end up being a long term contributor to this project.

Please provide me more information on this issue and how I can go about solving it. Thank you

**Comment by jondot** [comment]
Hi! so happy you want to jump onboard and happy to have you with us :)
@kaplanelad just finished this issue but something just as easy should be: https://github.com/loco-rs/loco/issues/174, please ask questions there and we will help
