### ISSUE TITLE
 Should devcontainer add remoteUser?

### ISSUE THREAD

**Issue by fan-tastic-z** [loco-rs/loco#186]
**Description**

```
(base)  ~/dev/ loco new                                                                                                   
✔ ❯ App name? · todolist
✔ ❯ What would you like to build? · Rest API (with DB and user auth)

🚂 Loco app generated successfully in:
/Users/fanzhao/dev/todolist
(base)  ~/dev/ cd todolist 
(base)  ~/dev/todolist/ code .     
(base)  ~/dev/todolist/ 
```

Use vscode to open in a container, vscode's rust-analyzer not working properly and cargo loco doctor has permission issues
![image](https://github.com/loco-rs/loco/assets/142720801/90e72651-bfff-48d4-bb27-72c13f8077b3)

```
vscode ➜ /workspaces/todolist $ cargo loco doctor
    Updating crates.io index
  Downloaded ptr_meta v0.1.4
error: failed to download replaced source registry `crates-io`

Caused by:
  failed to open `/usr/local/cargo/registry/cache/index.crates.io-6f17d22bba15001f/ptr_meta-0.1.4.crate`

Caused by:
  Permission denied (os error 13)
vscode ➜ /workspaces/todolist $ 
```

I add "remoteUser": "root" to devcontainer.json and it can return to normal.
Should remoteUser be added to the default devcontainer.json, or should the developer add it themselves? Or are there other ways to solve it?

**Comment by kaplanelad** [comment]
Hi @fan-tastic-z,

In the Dockerfile, when building, we have the option to grant write access to the vscode user in the /usr/local/cargo path. This should address the issue without the need to include removeUser: root.

Would you like to proceed with this solution and open a pull request?

**Comment by fan-tastic-z** [comment]
> Hi @fan-tastic-z,
> 
> In the Dockerfile, when building, we have the option to grant write access to the vscode user in the /usr/local/cargo path. This should address the issue without the need to include removeUser: root.
> 
> Would you like to proceed with this solution and open a pull request?


OK, I'd love to
