### ISSUE TITLE
docs-site  in the document, cargo loco is used uniformly.

### ISSUE THREAD

**Issue by fan-tastic-z** [loco-rs/loco#200]
**Description**

In the documentation, there are multiple references to both cargo loco generate... and loco generate... in Models and Migration.

Is it better to unify it?

![image](https://github.com/loco-rs/loco/assets/142720801/d7f92d40-4e5a-4892-a408-5e06ab4ae236)
![image](https://github.com/loco-rs/loco/assets/142720801/ad06f5e4-9599-4d3d-8b9f-426555426456)

**Comment by jondot** [comment]
yes my bad! I'm so used to it :)
will fix, thanks!

**Comment by jondot** [comment]
done
