### ISSUE TITLE
Deployment: add `nginx`

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#203]
Look here: https://github.com/clowzed/sero/blob/master/nginx-templates/default.conf.template

`sero` is very similar in stack: [Axum, SeaORM, Postgres](https://github.com/clowzed/sero/issues/18). They use nginx for deployment, which is something we could use as well.

The deployment should create

* nginx conf file file (look at what `sero` does)
* any local configuration tweaks that we need in order to work behind an nginx proxy (edit YAML for production, change it, write it back)
* try to do it all with our generator + code injections framework

**Comment by fivehanz** [comment]
+1

**Comment by arferreira** [comment]
Hey guys can I get this issue?

**Comment by kaplanelad** [comment]
Hey @arferreira, sure, go for it.
