### ISSUE TITLE
File uploads: add a paperclip like library

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#206]
see more here:
https://github.com/m1guelpf/flysystem/issues/2

it should be added as a first-class facility, `Option<..>` on `AppContext`, and have its own configuration section in `config/`

**Comment by tverghis** [comment]
Hi! I think supporting file uploads would be a great value-add for Loco. I was wondering if you had considered [object_store](https://docs.rs/object_store/latest/object_store/)? (no affiliation at all)

**Comment by yinho999** [comment]
@kaplanelad Hello here, I would like to work on this issue. Would you mind assign this issue to me please?

**Comment by kaplanelad** [comment]
sure, thanks @yinho999

**Comment by yinho999** [comment]
@jondot, could you clarify what 'T' represents in the App Context - Option<T>? Are you referring to the middleware-preprocessed files or the file builder itself?

According to the Axum documentation, multipart form data extraction must consume the request body, which necessitates the Multipart extractor being the final extractor in a handler chain. This implies that file preprocessing cannot occur within the middleware but must instead be handled directly within the handler.

To enhance usability, I recommend providing additional helper functions for the file builder.

For your reference, here is a simple test code example: https://github.com/yinho999/loco-playground/blob/master/src/bin/multipart.rs

**Comment by fan-tastic-z** [comment]
> see more here: [m1guelpf/flysystem#2](https://github.com/m1guelpf/flysystem/issues/2)
> 
> it should be added as a first-class facility, `Option<..>` on `AppContext`, and have its own configuration section in `config/`

Try adding flysystem to the project and find that there will be dependency conflicts.

```
vscode ➜ /workspaces/loco_admin (main) $ cargo add flysystem
    Updating crates.io index
      Adding flysystem v0.1.3 to dependencies.
             Features:
             + local
             + s3
    Updating crates.io index
error: failed to select a version for `flysystem`.
    ... required by package `loco_admin v0.1.0 (/workspaces/loco_admin)`
versions that meet the requirements `^0.1.3` are: 0.1.3

the package `loco_admin` depends on `flysystem`, with features: `tokio` but `flysystem` does not have these features.
 It has an optional dependency with that name, but that dependency uses the "dep:" syntax in the features table, so it does not have an implicit feature with that name.


failed to select a version for `flysystem` which could resolve this conflict
vscode ➜ /workspaces/loco_admin (main) 
```

**Comment by kaplanelad** [comment]
@fan-tastic-z i'm already working on this feature. 
I'm creating a crate that more fit more to our needs and integrate with the project. 

I'll upload a draft PR later on this week

**Comment by yinho999** [comment]
@kaplanelad Is there anything that I can help about ur crate? I was working on this issue for a couple days now.

**Comment by kaplanelad** [comment]
@yinho999 sure! 
i'll publish code to draft PR, you can do the same and we can compare the implementation and bring only the good stuff :)

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z i'm already working on this feature. I'm creating a crate that more fit more to our needs and integrate with the project.
> 
> I'll upload a draft PR later on this week

@kaplanelad Thank you very much, looking forward to this feature

**Comment by kaplanelad** [comment]
https://github.com/loco-rs/loco/pull/405

**Comment by kaplanelad** [comment]
new PR: https://github.com/loco-rs/loco/pull/423
