### ISSUE TITLE
Support ServeDir.html precompressed_gzip

### ISSUE THREAD

**Issue by ohaddahan** [loco-rs/loco#207]
Add support for  (don't think we need the other formats, keep it simple mindset): 
https://docs.rs/tower-http/latest/tower_http/services/struct.ServeDir.html#method.precompressed_gzip

There is one extra enhancement I think we can support, which is compress on the fly as in:

1. Check if gzip version of an asset exist.
2. If not, send to a bg job to compress it.
3. Next time it's been asked it will compress it.

This differ https://github.com/loco-rs/loco/pull/205 by that it will save time on compression, the middleware will incur compression overhead each request while with this way, we pay for it once.

(need to double check that `precompressed_gzip` skips the compression layer to avoid double compression for no need)

I can implement it if required.

**Comment by ohaddahan** [comment]
Just reread the docs
```
Assuming the dir directory is being served and dir/foo.txt is requested, a client with an Accept-Encoding header that allows the gzip encoding will receive the file dir/foo.txt.gz instead of dir/foo.txt. If the precompressed file is not available, or the client doesn’t support it, the uncompressed version will be served instead. Both the precompressed version and the uncompressed version are expected to be present in the directory. Different precompressed variants can be combined.
```

I think it's ok to have compression layer and this together seems to play fine in conjunction.

**Comment by jondot** [comment]
Doing a cleanup tour of issues, should we close this one?

**Comment by ohaddahan** [comment]
> Doing a cleanup tour of issues, should we close this one?

Sorry slipped my mind.
Started it at https://github.com/loco-rs/loco/pull/370 .
