### ISSUE TITLE
Add support for Socketioxide

### ISSUE THREAD

**Issue by tausifcreates** [loco-rs/loco#208]
## Feature Request

**Is your feature request related to a problem? Please describe.**

A batteries included framework for managing websockets with support for rooms/namespaces is a nice thing to have.

**Describe the solution you'd like**

I would like Loco to add support for [Socketioxide](https://github.com/Totodore/socketioxide), which is a [socket.io](https://socket.io/) server implementation that integrates with the [Tower](https://tokio.rs/#tk-lib-tower) ecosystem and the [Tokio stack](https://tokio.rs/). It has a very easy to use api. So an echo example with Socketioxide and Loco will suffice for how to get started.

**Comment by kaplanelad** [comment]
@tausifcreates  Socketioxide implemented in loco and going to be release in the next version

**Comment by kaplanelad** [comment]
@tausifcreates i want to open a pr in Socketioxide with loco example. what do you think?

**Comment by tausifcreates** [comment]
@kaplanelad Hey, first of all, thanks a lot for the efforts you guys put here! For adding an example part, please open a pr! 😄
