### ISSUE TITLE
A Quick Tour with Loco: Cannot register user

### ISSUE THREAD

**Issue by megastary** [loco-rs/loco#220]
**Description**

When following [A quick Tour with Loco](https://loco.rs/docs/getting-started/tour/), **Checking Out SaaS Authentication** part does not work as intented.

**To Reproduce**

Follow steps in documentation. In part Registering a New User and Login I get error:

HTTP/1.1 405 Method Not Allowed
allow: GET,HEAD
content-length: 0
date: Fri, 22 Dec 2023 18:17:04 GMT

**Expected Behavior**

Register user and login to obtain JWT token.

**Environment:**

- Windows 11
- rustc 1.74.1
- loco-rs 0.1.8

**Additional Context**

Also the guide seems already behind current version, as screenshot showing `loco new`  is different from current version. As someone who found out about loco from blog post, it's great tragedy to get stuck on first page of docs when I want to try it out and possibly like it (I really want, but those things make people turn away)

**Comment by kaplanelad** [comment]
Thanks @megastary for letting us know.  I missed the `/api/` prefix to all the requests.
I'll fix it

**Comment by kaplanelad** [comment]
@megastary I [pushed](https://github.com/loco-rs/loco/commit/522711084006b1c8d5f77199bb113688eee3f978) the changes now

I'll deploy it to the website soon.

**Comment by megastary** [comment]
> Thanks @megastary for letting us know. I missed the `/api/` prefix to all the requests. I'll fix it

You're right, that works.
One more thing though, in the Get current user section, as it's GET method, isn't there data part superfluous?

```shell
$ curl --location --request GET '127.0.0.1:3000/user/current' \
     --header 'Content-Type: application/json' \
     --header 'Authorization: Bearer TOKEN' \
     --data-raw '{
         "email": "user@loco.rs",
         "password": "new-password"
     }'
```

should be just 

```shell
$ curl --location --request GET '127.0.0.1:3000/api/user/current' \
     --header 'Content-Type: application/json' \
     --header 'Authorization: Bearer TOKEN' 
```

**Comment by kaplanelad** [comment]
yes, you are right. already did it in the commit. see it [here](https://github.com/loco-rs/loco/commit/522711084006b1c8d5f77199bb113688eee3f978#diff-02bd7fee9438c490f830771bd9be5216449b868b6d2413c2261e544d127306a6R184)
