### ISSUE TITLE
RFE: Please support cargo xtask build/install

### ISSUE THREAD

**Issue by tjyang** [loco-rs/loco#226]
## Feature Request

Pls support cargo xtask build/install, currently on cargo xtask test is supported.

**Is your feature request related to a problem? Please describe.**
```
[me@rocky9t01a loco]$ pwd
/home/me/github/learnrust/loco
[me@rocky9t01a loco]$ cargo xtask build
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/xtask build`
error: unrecognized subcommand 'build'

Usage: xtask <COMMAND>

For more information, try '--help'.
[me@rocky9t01a loco]$ cargo xtask
    Finished dev [unoptimized + debuginfo] target(s) in 0.12s
     Running `target/debug/xtask`
Usage: xtask <COMMAND>

Commands:
  test          Run test on all Loco resources
  bump-version  Bump loco version in all dependencies places
  help          Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version
[me@rocky9t01a loco]$
```
Provide a succinct and clear description of the problem. For example, I encounter an issue when...

**Describe the solution you'd like**

cargo xtask build
cargo xtask install
Articulate a clear and concise depiction of your desired outcome.

**Describe alternatives you've considered**
To get loco-cli built and installed currently
cd loco-cli;cargo install --path . or cargo build --release

Offer a clear and concise description of any alternative solutions or features you have contemplated.

**Comment by kaplanelad** [comment]
@tjyang xtask is a tool that we build for internal needs when you develop loco lib, and not connected directly to the starters/examples.
