### ISSUE TITLE
Mysql connection is not work

### ISSUE THREAD

**Issue by huturen** [loco-rs/loco#236]
**Description**
Mysql connection is not work.

![image](https://github.com/loco-rs/loco/assets/5173298/ef520da6-c9ee-467f-aa9a-0a12367a45a2)

**To Reproduce**
1. use mysql connection
![image](https://github.com/loco-rs/loco/assets/5173298/f58af90b-ba87-420e-bbcc-951d083fc20e)
2. `cargo loco start`

**Expected Behavior**

Mysql connection can be used.

**Environment:**
MacOs 14.1.1
cargo 1.74.0 (ecb9851af 2023-10-18)

**Comment by kaplanelad** [comment]
@huturen, by default, Loco starters come with PostgreSQL. If you want to work with MySQL, you should go to your Cargo.toml file and add the`sqlx-mysql` feature. For more details, refer to the SeaORM documentation [here](https://www.sea-ql.org/SeaORM/docs/next/install-and-config/database-and-async-runtime/#database_driver).

**Comment by huturen** [comment]
After adding the `sqlx-mysql` feature, it works.
