### ISSUE TITLE
Using `seed` with auto-increment PK means followup inserts fail on Postgres

### ISSUE THREAD

**Issue by felipesere** [loco-rs/loco#239]
**Description**

I ran the seed against a fresh loco SaaS app and then tried to register a new user.
I kept getting failures about duplicate keys for the `users_pkey`:

```
2023-12-26T09:42:02.160004Z  INFO http-request: foody::controllers::auth: could not register user Query Error: error returned from database: duplicate key value violates unique constraint "users_pkey" user_email="foo@example.com" http.method=POST http.uri=/api/auth/register http.version=HTTP/1.1 http.user_agent=HTTPie/3.2.2 environment=development request_id=34ff3ee8-5a66-47d9-989d-d07adf29ea3d
```

I had to go in an alter the sequence ID with 
```sql
ALTER SEQUENCE users_id_seq RESTART WITH 3
```

**To Reproduce**

Generate a new app, launch the databases, migrate and then seed them.
Then launch the application and try to register a new user as described in the docs.

**Expected Behavior**

I wish the the migration would in the end run
```sql
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));
```

I imagine this is pretty tricky to run generically. Maybe  part of the hooks can schedule some sql?

**Environment:**
any env with seeds.

Edit:
I added the following at the bottom of `async fn seed(...)` which is pretty nice:
```rust
        for table in ["users", "notes", "ingredients"] {
            db.query_one(Statement::from_string(DbBackend::Postgres, format!("SELECT setval('{table}_id_seq', (SELECT MAX(id) FROM {table}))"))).await?;
        }
```
Something more intelligent could try to query the schema to find autoincrementing IDs and reset them to their max values...

**Comment by kaplanelad** [comment]
Fixed: https://github.com/loco-rs/loco/pull/1014
