### ISSUE TITLE
RFE: Adding server IP address before port number in banner

### ISSUE THREAD

**Issue by tjyang** [loco-rs/loco#253]
## Feature Request

**Is your feature request related to a problem? Please describe.**
Adding server IP address before port number in banner.
Provide a succinct and clear description of the problem. For example, I encounter an issue when...

**Describe the solution you'd like**
Assume server IP=192.168.241.128
<snipped>
environment: development
   database: automigrate
     logger: debug
compilation: release
      modes: server

listening on 192.168.241.128  port 3000

Articulate a clear and concise depiction of your desired outcome.

**Describe alternatives you've considered**

Offer a clear and concise description of any alternative solutions or features you have contemplated.

**Comment by jondot** [comment]
Im not sure a server can know its address in a reliable form (internal or external), unless it was bound to a specific one, I think we always bind to 0.0.0.0. Did you look at that area?

**Comment by tjyang** [comment]
Default binding to 0.0.0.0 is most quick and easy way during development. But in production,  when a server has multiple net interfaces, loco  should be able to lock on particular interface when starting up.

- See blo-cli demo, may be -H and -p can be added as OPTIONS if one one to overwrite default 0.0.0.0:3000 ? 

```
[me@rocky9t01a demo]$ blo-cli
The one-person framework for Rust

Usage: blo-cli [OPTIONS] <COMMAND>

Commands:
  start     Start an app
  db        Perform DB operations
  routes    Describe all application endpoints
  task      Run a custom task
  generate  code generation creates a set of files and code templates based on a predefined set of rules
  doctor    Validate and diagnose configurations
  version   Display the app version
  help      Print this message or the help of the given subcommand(s)

Options:
  -e, --environment <ENVIRONMENT>  Specify the environment [default: development]
  -h, --help                       Print help
  -V, --version                    Print version
[me@rocky9t01a demo]$ blo-cli

```

**Comment by kaplanelad** [comment]
Done in pr: https://github.com/loco-rs/loco/pull/402
