### ISSUE TITLE
Add Support for TursoDB

### ISSUE THREAD

**Issue by martinsodabi** [loco-rs/loco#258]
## Feature Request

Please add support for TursoDB (A distributed SQLite cloud database). As far as I know, SeaORM already support SQLite but does not support Libsql (a fork of SQLite) url and auth token for remote connection.

A way this might be implemented is getting the raw sql query from SeaORM model operations and sending that through the remote Libsql database connection. Libsql is compliant with SQLite so all database operations should work as intended.

If this feature is not practical, please let me know of any work arounds and suggestions, or whether this is already possible, thanks.

**Comment by jondot** [comment]
Hi @martinsodabi
I heard about TursoDB but have not used it before. I'd be happy to see a PR if you want to work on this. The trick you're suggesting might work, but it requires motivation from someone using TursoDB

**Comment by jondot** [comment]
Closing for cleanups, if needed please reopen :heart:
