### ISSUE TITLE
Invalid Discord Invitation Link

### ISSUE THREAD

**Issue by yinho999** [loco-rs/loco#266]
**Description**

The discord invitation link in README.md is not working.

**To Reproduce**

Click the Discord Link in the README.md

**Expected Behavior**

Expected to redirect back to discord and join the group

**Environment:**

**Additional Context**

Need to update the discord link

![image](https://github.com/loco-rs/loco/assets/26657530/c4ced9e3-223b-41b6-b69d-99fb04ab3c13)

**Comment by fan-tastic-z** [comment]
Feel the need to generate a permanent request link

**Comment by kaplanelad** [comment]
Thanks @yinho999. the link was updated
