### ISSUE TITLE
App context available when routes are setup

### ISSUE THREAD

**Issue by futuretim** [loco-rs/loco#278]
I would like and think it would be helpful to be able to have configurable routes depending on the mode I want to run my application in this. To do this I would add it to settings and use those boolean (or other values) to determine the routes to hook up.

I can't do that currently because there is no app context available. I looked at doing it myself but it turned into a bit more because when the routes are listed from the `loco routes` command it doesn't have any app context to pass in.

If this is desirable I'll go back to modifying the framework to support this and deal with the route listing part also and submit a PR but I wanted a discussion before the work was done.

Alternatives:

- an alternative is to drive this behavior with environment variables, certainly functional but I deemed this as unacceptable because it disconnects some of the applications configuration from the normal place it should be: `settings`.

**Comment by jondot** [comment]
you mean you want to, say, expose some admin route when `development` but hide it when `production`?

**Comment by futuretim** [comment]
That could be one example. In this case whether registration is enabled or
not is what I was trying to support and either enabling or disabling a set
of routes based on that.

**Comment by jondot** [comment]
Yes, I think we can explore adding appcontext to `routes()`, from my initial checks there is not reason not to.
will schedule this item to v0.2.0
