### ISSUE TITLE
Add host definition to config options

### ISSUE THREAD

**Issue by mikosco4real** [loco-rs/loco#281]
I am trying to deploy my loco app in fly.io and it appears they require connection to be in this form 
```rust
tokio::net::TcpListener::bind(&format!("[::]:3000", config.server.port)).await?;
```

instead of this
```rust
tokio::net::TcpListener::bind(&format!("0.0.0.0:{}", config.server.port)).await?;
```

Request to add web server host definition in the .config/*.yaml files

**Comment by mikosco4real** [comment]
Hello @jondot and @kaplanelad,

I've been working on addressing the deployment issue on fly.io, where the platform requires an IPv6 format for binding the server. I've identified two potential approaches to resolve this and would appreciate your insights to determine the best path forward.

**Approach 1: Direct Replacement**
The simplest solution is to replace the hardcoded string from "0.0.0.0:{PORT}" to "[::]:{PORT}". This change is quick, straightforward, and ensures compatibility with both IPv6 and IPv4. However, it's less flexible and doesn't account for future or custom configurations.

**Approach 2: Configurable Binding**
A more flexible solution would be to make the binding address configurable. We could introduce a new configuration parameter, such as "address" in the server section of our config files. This would allow users to specify the desired binding address directly. However, there are a few challenges:
- **Naming**: We already have a "host" definition in our config. We need to ensure that the new parameter is clearly distinguished and understood.
- **Backward Compatibility**: Making "address" an optional configuration is crucial to avoid breaking changes for current users of loco-rs.

I lean towards the second approach due to its flexibility and adaptability to various deployment environments. However, I recognize that the first approach might suffice for most typical use cases.

I would greatly value your thoughts on these options. Are there any considerations or preferences from your side that might steer this decision?

**Comment by jondot** [comment]
Thanks for the detailed analysis, I think approach (1) is what Rails does. Rails also provides a `-b` CLI parameter to override binding, and from what I'm looking at - I can't find if they provide binding arguments via config.

In configuration, they have something else which is interesting, which is this: https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization

So all in all, to do the simplest thing - I think I would go for (1), knowing that in the future we will add many more host-like configuration, from Rails I already see:

1. host authorization
2. asset host

and maybe more

**Comment by jondot** [comment]
I think we now support `::`, so closing this one, thanks!
