### ISSUE TITLE
Deployment: traefik

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#283]
As suggested in one of the PRs, add a traefik deployment

**Comment by mikosco4real** [comment]
@jondot , can you explain in detail what is required here? I believe when you say traefik you are referring to the proxy and load balancing tool built in golang.

**Comment by kaplanelad** [comment]
The Traefik configuration is a generic setup that you configure on the proxy and register through labels. Currently, there isn't anything specific that we can offer. If you have any ideas, please feel free to open this issue and share your thoughts. Your input
