### ISSUE TITLE
Support custom loaders for db::seed

### ISSUE THREAD

**Issue by Warchant** [loco-rs/loco#296]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Current `seed` function has following definition:
```rust
pub async fn seed<A>(db: &DatabaseConnection, path: &str) -> AppResult<()>
where
    ...
{
    let loader: Vec<serde_json::Value> = serde_yaml::from_reader(File::open(path)?)?;
```

Note how loader is always using yaml. 

**Describe the solution you'd like**

CSV files are a better fit for a seed data IMO. 
Other people may want to use something else.

This issue is a request to replace current `seed` with these 3 definitions:

```rust
// current `seed` renamed:
pub async fn seed_from_yaml<A>(db: &DatabaseConnection, path: &str) -> AppResult<()>
// same, but reads csv instead of yaml
pub async fn seed_from_csv<A>(db: &DatabaseConnection, path: &str) -> AppResult<()>
// does same as `seed`, does not use files for seeding.
pub async fn seed<A>(db: &DatabaseConnection, entities: &[A]) -> AppResult<()>
```

- this keeps current `seed` function (at a cost of a function rename)
- adds CSV seeding capabilities
- adds ability to seed from any source. E.g. read whatever source you like, transform into `A`, call `seed`.

I will be happy to work on this, I only need an approval to rename `seed` -> `seed_from_yaml`.

**Comment by kaplanelad** [comment]
Hey @Warchant,
Thanks for the idea, this is something that we can support.

Would you like to open a pull request?

**Comment by kaplanelad** [comment]
Instead of supporting multiple formats, we’ve introduced the option to export data from the database into a YAML file.

PR: #1017
