### ISSUE TITLE
Mailer disable with default CLI configuration

### ISSUE THREAD

**Issue by yinho999** [loco-rs/loco#298]
**Description**

The default CLI command `cargo loco start` cannot start the mailer by default since the command does not start workers in the background. To start the mailer, we need to use `cargo loco start --server-and-worker`. 

Also, there is a default sender email `System <system@example.com>` located within "src/mailer/mod.rs" is requires to be changed before actually sending the email.

**To Reproduce**

Start the server with `cargo loco start`, no email has been sent.

**Expected Behavior**

We should add `cargo loco start --server-and-worker` within the Mailer documentation to avoid confusion. Also, we should add a note to remind developers to change the default email.

**Environment:**

**Additional Context**

In the future, we can add the default sender email to the `config/*yaml` as part of the configuration.

**Comment by kaplanelad** [comment]
Related PR: #313
