### ISSUE TITLE
Floats not supported in model generation

### ISSUE THREAD

**Issue by futuretim** [loco-rs/loco#307]
Unless I'm mistaken given the latest [schema](https://docs.rs/loco-rs/0.1.9/loco_rs/schema/index.html) f32 and f64 are not supported for mapping when generating a new model.

You can of course work around this by directly using SeaORM's ColumnDef::new directly instead and using the float function on it to set its type but this certainly breaks the usability for users because now it's a mixture of Loco and SeaORM.

I suspect this needs to be added? Please correct me if I'm wrong. Thanks!

**Comment by jondot** [comment]
Yes, it can be added.
Would you like to work on it and submit a PR?

**Comment by slyons** [comment]
I had to do this workaround myself. If I get time I might be able to add it
