### ISSUE TITLE
Ensuring JSON Schema Response for Failed Payload Deserialization in Controller

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#309]
We need to implement a mechanism that catches the server response when JSON schema response when the payload received by the controller does not match the expected schema.

How to Reproduce:
For instance, consider the example/demo project and initiate the server.

Then, execute the following request:

```sh
curl -XPOST -H 'Content-Type: application/json' --data '{"test":"test"}' 127.0.0.1:3000/auth/register
```

The response will be:
```
Failed to deserialize the JSON body into the target type: missing field `email` at line 1 column 15%
```

To address this issue, it is essential to capture the error and return a default JSON schema response, similar to the example found [here](https://github.com/loco-rs/loco/blob/master/src/controller/mod.rs#L179).

**Comment by arferreira** [comment]
Hey @kaplanelad taking this lol

**Comment by kaplanelad** [comment]
@arferreira note that I've already implemented this feature
