### ISSUE TITLE
`Vec<u8>` cannot be formatted with the default formatter

### ISSUE THREAD

**Issue by huturen** [loco-rs/loco#312]
**Description**
An error(**`Vec<u8>` cannot be formatted with the default formatter**) is thrown after generating models.
![image](https://github.com/loco-rs/loco/assets/5173298/cf997a0b-fc44-42bc-80fd-b5ceb23cd673)

Code as below:
```rust
async fn verify(
    State(ctx): State<AppContext>,
    Json(params): Json<VerifyParams>,
) -> Result<Json<()>> {
    let user = users::Model::find_by_verification_token(&ctx.db, &params.token).await?;

    if user.email_verified_at.is_some() {
        tracing::info!(pid = user.pid.to_string(), "user already verified");
    } else {
        let active_model = user.into_active_model();
        let user = active_model.verified(&ctx.db).await?;
        tracing::info!(pid = user.pid.to_string(), "user verified");
    }

    format::json(())
}
```
**To Reproduce**

1. use mysql connection
![image](https://github.com/loco-rs/loco/assets/5173298/72e3c847-5f08-4a88-82ee-a309b974bffb)

2. `cargo loco generate model posts`
3. `cargo loco start`

**Expected Behavior**

There are no errors after executing the `cargo loco start` command.

**Environment:**

MacOs 14.1.1
cargo 1.74.0 (ecb9851af 2023-10-18)

**Comment by jondot** [comment]
try working with tracing debug formatting, like this `greeting = ?my_struct` (notice the `?` symbol)

```rust
event!(Level::TRACE, greeting = ?my_struct);
```

**Comment by kaplanelad** [comment]
@huturen closing this issue. 
if you still have a problem feel free to re-open this issue with more details
