### ISSUE TITLE
get_env doesn't read value from .env

### ISSUE THREAD

**Issue by yuki0418** [loco-rs/loco#315]
**Description**
I start `rest-api` with changing `DATABASE_URL` in `.devcontainer/.env` and add `.env` at root as well.
Then run `cargo loco start`, however `get_env` in `config/development.yml` still read default value.
When I change `config/development.yml` directly, it works well as expected.

I'm not sure if its expected or a bug.
Apologize if I miss the documentation, I'm newbie.

https://github.com/loco-rs/loco/blob/5da37a4f4f6f0906bc11aae5025bd063186d8d77/starters/rest-api/config/development.yaml#L89

**To Reproduce**
1. Change  `.devcontainer/.env`
```
DATABASE_URL=postgres://user:password@db:5432/test_db_name
```
2.  Run `cargo loco start` or any equivalent to access to database.

**Expected Behavior**
`get_env` should read environment values from `.env` ?

**Environment:**
development

**Additional Context**

**Comment by kaplanelad** [comment]
Hey, @yuki0418`get_env` is not reading from the `.env` file. you need to make sure that you populate the `.env` cat into the loco process. 
you can try this:
```
 env $(cat .env) cargo loco start
 ```

**Comment by yuki0418** [comment]
Hi, @kaplanelad 
Thank you so much.
It works well!

I just wonder, will you add feature to read .env in future?
If not, may I ask you any reasons for that? Because there may many cases to use .env file in dev, in my opinion.

**Comment by yuki0418** [comment]
I add `dotenv` and add `dotenv().ok();` in `config.rs`, it reads env values from .env.
Adding `dotenv` is one of option for Loco maybe if want the feature.

**Comment by kaplanelad** [comment]
@yuki0418, it's fantastic to see it work for you. Our goal is to keep the library as compact as possible, avoiding the import of unnecessary crates.

In this situation, you can effortlessly integrate the .env library into your application and tailor it to your specific requirements.

**Comment by alexhumphreys** [comment]
@yuki0418 i'm running into the same issue trying to use the [dotenvy](https://github.com/allan2/dotenvy) library. When you say "I add dotenv then modify config.rs to run `dotenv().ok();`" do you mean that you're modifying the loco library [config.rs file](https://github.com/loco-rs/loco/blob/master/src/config.rs), or something else? If so, does that mean you have to run a patched version of loco?
It looks like config is loaded pretty early in the [`scr/cli.rs`](https://github.com/loco-rs/loco/blob/master/src/cli.rs#L293) file, before commands are parsed, so I don't think anything in my [`src/app.rs`](https://github.com/loco-rs/loco/blob/master/examples/demo/src/app.rs) can run before that, and I'd rather not patch loco to achieve this...

**Comment by yuki0418** [comment]
> alexhumphreys
Yes, I edit `src/config.rs` of loco library directory then add `dotenv().ok()` at below line.
https://github.com/loco-rs/loco/blob/b84ca58ecf24a3fd83b7491566af647b4f9dd66f/src/config.rs#L489

But it was just for checking so the best practice would be following loco's way which is using config files that you can have a look in example folder I think.
