### ISSUE TITLE
Add Json field support in model generation

### ISSUE THREAD

**Issue by isaacdonaldson** [loco-rs/loco#320]
I see there is no support for the PostgreSQL `jsonb` type in the [schema](https://docs.rs/loco-rs/latest/loco_rs/schema/index.html) for generating a new model. I see another issue #307 about adding a Float (and potentially a Date). I have been adding the `jsonb` support for my own projects through SeaOrm's [Json](https://docs.rs/sea-query/0.28.5/sea_query/value/enum.Value.html#variant.Json) type.

I don't mind taking this on myself, especially since the way will be paved when the Float support is added, would just want to know if this is something you would be okay with adding.

To add some clarity, I am talking about adding the json binary type support and after looking at the SeaOrm docs this might(?) require introducing a new crate feature. I am also unsure if sqlite supports json binary.

**Comment by kaplanelad** [comment]
Hey @isaacdonaldson
Yes, it can be great.

Can you open a pull request?

**Comment by shuvroroy** [comment]
@kaplanelad can I?

**Comment by kaplanelad** [comment]
@shuvroroy sure
