### ISSUE TITLE
warning: unused variable: `app_context` in example/demo/src/tasks/foo.rs:14:25

### ISSUE THREAD

**Issue by tjyang** [loco-rs/loco#322]
**Description**
warning: unused variable: `app_context`

**To Reproduce**
cd example/demo && cargo build

**Expected Behavior**

No warning message

**Environment:**
[demo]$ git log -1
commit c06223c2486dfb1db5bf9586d2b15c3ad6c6c969 (HEAD -> master, origin/master, origin/HEAD)
Merge: 5da37a4 dcda4c8
Author: Elad Kaplan <kaplan.elad@gmail.com>
Date:   Thu Jan 4 04:51:47 2024 -0800

    Merge pull request #314 from fan-tastic-z/feat-devcontainer-add-insta

    feat: starters devcontainer Dockerfile install cargo-insta
[demo]$

**Additional Context**
Sorry, I don't know how to fix this warning message to submit a PR myself.

**Comment by kaplanelad** [comment]
@tjyang 
I am closing this issue. The code in the demo is intended for debugging and testing purposes and should not be propagated to the library. You are more than welcome to open a pull request for its removal.
