### ISSUE TITLE
Document how to work with `ApiToken`

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#325]
Loco offers two middleware options for authentication:

1. Authentication based on a username and password, with detailed documentation available [here](https://loco.rs/docs/features/authentication/#get-current-user).

2. Authentication based on a user API token, which is currently not documented on loco.rs.

Needs to document the authentication method based on API tokens. The relevant code reference is in the [middleware implementation](https://github.com/loco-rs/loco/blob/master/src/controller/middleware/auth.rs#L140).

For a practical example of implementing this middleware, refer to the following code snippet in the [user controller](https://github.com/loco-rs/loco/blob/master/examples/demo/src/controllers/user.rs#L13).

**Comment by yuki0418** [comment]
@kaplanelad 
I'm a new so can try this.

**Comment by kaplanelad** [comment]
Hey @yuki0418, no problem at all! I'd be happy to assist you, and we can tackle this together.

Let's follow these steps:

1. Begin by creating a new project using `loco new`. Choose either saas or rest when prompted.
2. Register a new user by referring to the documentation [here](https://loco.rs/docs/features/authentication/#registering-a-new-user).
3. Once you've made the request, check the database to ensure that the user you created has an api_token stored.
4. Next, create a new endpoint similar to this [example](https://github.com/loco-rs/loco/blob/master/examples/demo/src/controllers/user.rs#L13), configuring the auth middleware with the API token.

Once you've successfully navigated through these steps, you're ready to start creating the documentation :) Feel free to reach out if you encounter any issues.

**Comment by yuki0418** [comment]
@kaplanelad 
Thank you so much for leading me!!

I check current user controller API code in demo and it uses `auth::JWTWithUser<users::Model>` for `current fn` [here,](https://github.com/loco-rs/loco/blob/006f532b0cef2ff0838ca7c0f9e40a66fe7f1a3a/examples/demo/src/controllers/user.rs#L6C1-L6C1) however, the current doc([here](https://github.com/loco-rs/loco/blob/006f532b0cef2ff0838ca7c0f9e40a66fe7f1a3a/docs-site/content/docs/features/authentication.md?plain=1#L168)) shows `auth: middleware::auth::Auth,`.
I guess the doc is old, so I will fix it too. Tell me if it not necessary. 

(user controllers in staters use still `auth::JWT`. I assume it is just before fix.)

**Comment by yuki0418** [comment]
Now I successfully checked new `ApiToken` middleware, so move on fix doc.

**Comment by yuki0418** [comment]
@kaplanelad 
I create PR so please check it when you can.
#328
