### ISSUE TITLE
Error in listening address on Windows

### ISSUE THREAD

**Issue by ryankopf** [loco-rs/loco#346]
This change: https://github.com/loco-rs/loco/commit/f8e9cea8177983e9629345bd62d91962c5a1c42d

Makes it so that http://127.0.0.1:3000/ refuses to connect.

You can still connect by using http://localhost:3000/ but this is very non-idiomatic and many people are going to try http://127.0.0.1:3000/ and be frustrated.

Does the same problem happen on Linux as well?

**Comment by mikosco4real** [comment]
@ryankopf I just tried on my macbook air M1. Both http://127.0.0.1:3000/ and http://localhost:3000/  worked for me.

**Comment by ryankopf** [comment]
> @ryankopf I just tried on my macbook air M1. Both http://127.0.0.1:3000/ and http://localhost:3000/ worked for me.

Can you confirm you are using the latest changes from the master branch? The error does not appear in the published 0.1.9 version, so if you are just calling "cargo loco new" then "cargo loco start" using the existing CLI, this hasn't been changed yet.

**Comment by mikosco4real** [comment]
yes, I used the demo within the master branch to test it. It works on Macs, and most likely will also work on Linux.

**Comment by Curry44424** [comment]
having same problem on windos will not connect to database are you guys just using Linux or ubuntu

**Comment by Curry44424** [comment]
runtime cost for production. disable with `logger.pretty_backtrace` in your config yaml)
Error: Connection Error: error returned from database: password authentication failed for user "loco"

Caused by:
   0: error returned from database: password authentication failed for user "loco"
   1: error returned from database: password authentication failed for user "loco"
   2: password authentication failed for user "loco"
getting this error after im using docker

**Comment by mikosco4real** [comment]
@Curry44424, looks like you do not have the correct credentials set up for Database connection. Few questions:

1. How are you running your database server? (Via Docker or installed locally to your windows?)
2. Are you able to connect to your database using any database tool or terminal?
3. If your application does not require database, have you considered our lightweight-service starters?
4. If you are able to connect to your database using any other tool, did you export your DATABASE_URL in your environment variables?

I can guide you on how to fix the problem with database if I get more context.

**Comment by Curry44424** [comment]
yea so I need rest api for  backend only my frontend is in flutter  my issue is connecting the PostgreSQL instance from docker with the redis instance from docker, its been giving me so many problems I assumed it was from docker but i also have PostgreSQL downloaded locally but i have been getting problems with docker and local database

**Comment by mikosco4real** [comment]
@Curry44424, One potential problem I can see with running postgresql in both docker and local is that you will run into a port clash. Postgresql default port is 5432, if the post is default for both docker and local, then one of them will not work properly. To solve this problem, you can set up your docker postgres to run on a different port, say 10000, then make sure that it is exposed to the host machine. One of the best ways I find to spin up docker is to use docker compose file. To that effect, you may consider to use the .devcontainer that comes with your loco initialised project. 

Here is what I would do.
Steps:
1. Edit your `.devcontainer -> dockercompose.yml` file. modify the db section to look like this:
```yaml
. . .
  db:
    image: postgres:15.3-alpine
    restart: unless-stopped
    ports:
      - 10000:5432
    networks:
      - db
. . .
```
2. Edit the `.devcontainer -> .env` file and modify your `DATABASE_URL` change the port number from 5432 to 10000
3. build and start the docker containers using the terminal command below while inside of the .devcontainer 
```bash
docker compose up -d --build
```
4. Go back to the root of your project and export the `DATABASE_URL` to your environment variables. Not sure what the command is in Windows. In unix systems it is something like 
```bash
export DATABASE_URL=postgres://postgres:supersecretpassword@db:10000/loco
5. Run your application to take advantage of both Postgresql database and redis with background workers using the command
```bash
cargo loco start --server-and-worker
```

This should get your application running. Reach out if there is any difficulty on your way.

**Comment by Curry44424** [comment]
okay thank you have been amazing help will reach out if incur any more problems

**Comment by Curry44424** [comment]
followed the directions it did the build command but I'm still getting a "no configuration file found " when I run it from vscode when I run it from gitbash :
runtime cost for production. disable with `logger.pretty_backtrace` in your config yaml)
Error: Connection Error: pool timed out while waiting for an open connection

Caused by:
   0: pool timed out while waiting for an open connection
   1: pool timed out while waiting for an open connection

ran it from the dev container.json and YAML

**Comment by Curry44424** [comment]
OMG thank you for your help ran each step and it finally open the app its running I really appreciate the help love what you guys have built

**Comment by jondot** [comment]
Thanks @ryankopf. We will add an issue to add a `bind` flag (`-b`, etc) where you can specify the entire interface binding expression
