### ISSUE TITLE
Documentation issues with Tour and Loco Guide

### ISSUE THREAD

**Issue by KnowZero** [loco-rs/loco#359]
https://loco.rs/docs/getting-started/tour/

When you get to the "Checking Out SaaS Authentication" section, it says nothing about starting up Redis docker so you get a bb8 timeout error

Also, the example mostly sets up a backend for a blog, with no front end. It probably should be clear that it is a backend of a blog so someone doesn't think something isn't working when they don't see a full blog

https://loco.rs/docs/getting-started/guide/

To test the examples, I created myapp_guide in the same folder so it doesn't conflict with the above folder

When I did `cargo loco doctor`, it gives this error:
```
error: unrecognized subcommand 'doctor'

Usage: myapp_guide-cli [OPTIONS] <COMMAND>

For more information, try '--help'.
```
Note: In the example of the blog backend, it works fine

curl localhost:3000/api/_ping
and
curl localhost:3000/api/_health

also do not work, and like above they work for the blog backend example

If I do `cargo loco routes`, it is missing from the routes:
[GET] /api

PS It is not clear if documentation issues should be posted here, discussions, or some other place, sorry if this is the wrong place

**Comment by kaplanelad** [comment]
Hey @KnowZero
about the Redis documentation, do you want to open a pull request with this addition?

for the `cargo loco doctor` which starter are you selected? can you share with me the `--help` output?

**Comment by KnowZero** [comment]
Sure, I can do that for the Redis. What about changing blog to "blog backend" part? Like so:

Let's create a blog on `loco` in 4 commands. First install `loco-cli` and `sea-orm-cli`:

to

Let's create a blog backend on `loco` in 4 commands. First install `loco-cli` and `sea-orm-cli`:

Should I do that too?

For the starter, I picked the one mentioned in the guide "lightweight-service (minimal, only controllers and views)"

Here is Help:
```
myapp_guide → cargo loco help
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `target/debug/myapp_guide-cli help`
The one-person framework for Rust

Usage: myapp_guide-cli [OPTIONS] <COMMAND>

Commands:
  start     Start an app
  routes    Describe all application endpoints
  task      Run a custom task
  generate  code generation creates a set of files and code templates based on a predefined set of rules
  version   Display the app version
  help      Print this message or the help of the given subcommand(s)

Options:
  -e, --environment <ENVIRONMENT>  Specify the environment [default: development]
  -h, --help                       Print help
  -V, --version                    Print version
```

**Comment by kaplanelad** [comment]
If you opt for the lightweight-service option, the starter will be provided without the with-db feature. In this case `doctor` command is unnecessary (you don't have db + seaorm).


Regarding the docs changes it should good and small change. you can open us PR and move this conversation to PR
