### ISSUE TITLE
add `-b` flag to bind to interface

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#361]
Context: https://github.com/loco-rs/loco/issues/346

While we don't know why Windows behaves this way, adding a `-b` flag is useful as it adds parity with other frameworks.

Note: `-b` should **only** specify the interface. Port should not be affected. This is similar to Rails.

**Comment by mikosco4real** [comment]
@jondot you can assign this one to me. Let me attempt to solve it. 

I think the final goal will be to run your server with a command like

```bash
cargo loco start --server-and-worker -b 0.0.0.0
```

OR
```bash
cargo loco start --server-and-worker --binding=0.0.0.0
```

**Comment by jondot** [comment]
correct. I will assign to you. thanks for helping out!

**Comment by kaplanelad** [comment]
https://github.com/loco-rs/loco/pull/402
