### ISSUE TITLE
Password salting

### ISSUE THREAD

**Issue by Borderliner** [loco-rs/loco#376]
Salting is a fundamental feature in encrypting sensitive information such as user passwords. It seems strange not to have it by default when generating a working app. Could you please add password salting to the defaults? Thanks.

**Comment by jondot** [comment]
Thanks,
There's one dilemma of salting, where is how or where to keep the salt.
Do you have a preferred way or a strong opinion of it?

**Comment by jondot** [comment]
Closing for now, please reopen if needed 👍
