### ISSUE TITLE
static file

### ISSUE THREAD

**Issue by shinriyo** [loco-rs/loco#384]
## Feature Request

**Is your feature request related to a problem? Please describe.**

I want to put static file like css or png

**Describe the solution you'd like**

useful static folder to put our png or css files.

**Describe alternatives you've considered**

```
<img width="150" src="/static/loco.png"/>
```

**Comment by jondot** [comment]
it should work
is it possible for you to create a public repo with your project so we can run it to debug the issue?

**Comment by shinriyo** [comment]
@jondot 

I tried to new repository to show you.
But it made a new project but  it automatically created `static` section in `config/development.yaml` file.

I found that `loco-rs` version "0.1.6"  can't use static files, but  `0.2.2` can.

```
[dependencies]

#loco-rs = { version = "0.1.6" }
loco-rs = { version = "0.2.2" }
```

```
[dev-dependencies]

#loco-rs = { version = "0.1.6", features = ["testing"] }
loco-rs = { version = "0.2.2", features = ["testing"] }
```



```
use loco_rs::{
    app::{AppContext, Hooks},
    // added below
    boot::{create_app, BootResult, StartMode},
    controller::AppRoutes,
    db::{self, truncate_table},
    // added below
    environment::Environment,
    task::Tasks,
    worker::{AppWorker, Processor},
    Result,
};
// added below
use migration::Migrator;
use sea_orm::DatabaseConnection;
```


```
#[async_trait]
impl Hooks for App {
    fn app_name() -> &'static str {
        env!("CARGO_CRATE_NAME")
    }

    // added
    fn app_version() -> String {
        format!(
            "{} ({})",
            env!("CARGO_PKG_VERSION"),
            option_env!("BUILD_SHA")
                .or(option_env!("GITHUB_SHA"))
                .unwrap_or("dev")
        )
    }

    // fn boot(mode: StartMode, environment: Environment) -> BootResult {
    // added
    async fn boot(mode: StartMode, environment: &Environment) -> Result<BootResult> {
        // create_app::<Self, Migrator>(mode, "develop").await
        create_app::<Self, Migrator>(mode, environment).await
    }
```

I put image file like `octcat.jpg` `frontend/dist/assets` in the folder which has `Cargo.toml` file.

I works finally!!! thank you.

the address is `http://localhost:3000/assets/octcat.jpg`.

**Comment by jondot** [comment]
great happy it works for you!
