### ISSUE TITLE
channels: turn MessageStore into trait

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#386]
Then supply:

* `InMemoryMessageStore`: inprocess/current process persistence of messages
* `DBMessageStore`: hooks into our DB implementation, also provides table migrations, through a generator

Notes:

* In both cases we should strive for most of the logic to turn into a generic logic that appears in the framework, and then some "glue" that appears in code that is generated.
* Once we use a `MessageStore` trait, we can now provide event handlers as well, by chat models. Because we set up the trait in `app.rs` this can seamlessly persist data to DB, and the user configures almost nothing to get a fully functioning chat.
  * `SingleRoomChatModel` - `join` leaves all channels, then joins a selected room, `message` appends a message
  * `MultiRoomChatModel` - `join` joins a new room, `message` selects which room to append to, `leave` leaves a room

**Comment by kaplanelad** [comment]
[see ](https://github.com/loco-rs/loco/issues/892)
