### ISSUE TITLE
type: text! not found

### ISSUE THREAD

**Issue by slyons** [loco-rs/loco#388]
**Description**

When creating a new model, according to the docs I can use `text!` to create a non-null text field. This is not currently supported by the CLI. (Just plain `text` is)

**To Reproduce**

`cargo loco generate model items name:string! description:text! quantity:int! size:tiny_integer! infinite:bool!`

**Expected Behavior**

To remove the unsupported field type from the documents or support nullable `TEXT` fields

**Comment by jondot** [comment]
yes, the assumption was that a large text field would almost always be optional.
if you believe there are enough cases for it to be mandatory -- we would accept a PR if you want to contribute

**Comment by slyons** [comment]
It's also a matter of me not updating loco! 
Although now I've got a new bug to wrangle. This code is generated by the project's CLI, I would think it should just build:

```rust
error[E0425]: cannot find function `text_null` in this scope
  --> migration/src/m20240123_152813_items.rs:17:26
   |
17 |                     .col(text_null(Items::Description).borrow_mut())
   |                          ^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `tiny_integer` in this scope
  --> migration/src/m20240123_152813_items.rs:19:26
   |
19 |                     .col(tiny_integer(Items::Size).borrow_mut())
   |
```

**Comment by jondot** [comment]
correct, we move fast: https://github.com/loco-rs/loco/blob/04ef328cdf3938297a75660607cba1002dd1c5b4/src/gen/model.rs#L27-L28

try updating

**Comment by slyons** [comment]
Updating to 0.2.2 isn't actually reflecting in my code for some reason. I'll investigate this separately
