### ISSUE TITLE
`loco generate model --migration` for migration only

### ISSUE THREAD

**Issue by fan-tastic-z** [loco-rs/loco#400]
**Description**

Currently, if cargo loco generate model posts does not have fields, a migration file will be generated and written to automatically execute the migration. During development, I usually think of generating the migration file first, then writing the fields one by one, and then manually Execute cargo loco db migrate.
Now if I write less fields in cargo loco generate model posts due to imperfect considerations, I must enter the database to delete the records.
Moreover, a table may have many fields during development. If the cargo loco generate model brings all the fields, it will easily become very long.
Whether to consider cargo loco generate model if it does not automatically execute cargo loco db migrate when it does not carry fields?

**Comment by jondot** [comment]
We can add a flag `loco generate model --migration` which means "generate only migration" and do not automatically generate the model.
Would that be OK?

**Comment by fan-tastic-z** [comment]
> We can add a flag `loco generate model --migration` which means "generate only migration" and do not automatically generate the model. Would that be OK?

@jondot Yes, I think that's okay
