### ISSUE TITLE
Feature gate for Redis/Async Workers

### ISSUE THREAD

**Issue by slyons** [loco-rs/loco#404]
## Feature Request

Currently right now the `with-db` feature gate, the `_health` endpoint tries to connect to Redis. Problem is I'm not using Redis, I don't even have an instance of Redis spun up.

**Describe the solution you'd like**

Another feature gate for Async Workers so that the Redis health check / worker startup can be skipped

**Comment by jondot** [comment]
I believe if you remove the Redis configuration from your config YAML, the endpoint will not try to ping Redis.
Redis is optional in the config.

**Comment by kaplanelad** [comment]
After my check when redis is None, we are not doing a health validation in the endpoint. see it [here](https://github.com/loco-rs/loco/blob/master/src/controller/health.rs#L27)

I'm closing this ticket. @slyons if you have problem write more information and reopen this ticket
