### ISSUE TITLE
`cargo run -- down` doesn't revert a migration

### ISSUE THREAD

**Issue by BWStearns** [loco-rs/loco#409]
**Description**

The instruction to run a down migration is [here](https://github.com/loco-rs/loco/blob/eb7b7bdc3b2bfb0d9217655119068a629cc1f17c/starters/saas/migration/README.md?plain=1#L20) but it doesn't work.

The result is

```
warning: `my_app` (lib) generated 11 warnings (run `cargo fix --lib -p my_app` to apply 10 suggestions)
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/my_app-cli down`
error: unrecognized subcommand 'down'

Usage: my_app-cli [OPTIONS] <COMMAND>
```

**To Reproduce**

Run `cargo run -- down`

**Expected Behavior**

Revert last migration

**Environment:**

Dev

**Comment by jondot** [comment]
The migrator framework is actually very powerful, see here for the `up` direction (from Loco codebase)

<img width="501" alt="image" src="https://github.com/loco-rs/loco/assets/83390/9a9379fe-32a8-4286-9b04-245ff2da45ba">

We tried to hide the complexity and offer only "up", assuming mostly people fix "up" mistakes in production by applying another migration on top of the bad one -- thus, still go always "up".
Rarely did I use "down" migrations in Rails, so we're trying to delay their use as much as possible.

If you'd like to submit a PR that implements the "down" part we'd be happy to accept (it's mostly just copy-paste code and issuing calls to the migrator framework)

**Comment by BWStearns** [comment]
I'll get a PR for that in. I will never in my life get a generation command right on the first try so it's important for me to be able to run the down command for convenience 😆

**Comment by BWStearns** [comment]
Started it [here](https://github.com/loco-rs/loco/pull/414)

**Comment by BWStearns** [comment]
Finished up the down command: https://github.com/loco-rs/loco/pull/414

**Comment by kaplanelad** [comment]
this issue was merge and released
