### ISSUE TITLE
Generate scaffold with date doesn't generate controller

### ISSUE THREAD

**Issue by johanvaneck** [loco-rs/loco#450]
**Description**

When running the following in cli, the model is created, but no controller:

```
cargo loco generate scaffold event date:date title:text! description:text
```

I assume it happens because of the `date` type, because when I run the following, it works as expected:

```
cargo loco generate scaffold test test:text
```

**To Reproduce**

Run the above mentioned command in a new project.

**Expected Behaviour**

I expect that an events controller would be generated.

**Environment:**
Fresh project.

**Comment by clefelhocz2** [comment]
@jondot I looked at this problem and noted that https://github.com/loco-rs/loco/blob/master/src/gen/scaffold.rs#L28 and https://github.com/loco-rs/loco/blob/master/src/gen/model.rs#L21 differ in the types they allow.   I could work on trying to update scoffold.rs but wasn't sure if there were any other implications.  

Before I go creating a PR is there any other guidance you would give (or other issue to possibly tackle).

**Comment by schungx** [comment]
The scaffold appears to be an out-dated version that is no longer in sync.  I have stopped using scaffold altogether, and rely on manually editing the source files.
