### ISSUE TITLE
 `storage::drivers::aws::new` support cover endpoint ?

### ISSUE THREAD

**Issue by fan-tastic-z** [loco-rs/loco#453]
## Feature Request

In development, local minio container is usually used to store small files, so should you consider adding an endpoint to overwrite the endpoint?
At present, I see that aws::new in the loco source code does not allow overwriting endpoints.

```
/// Create new AWS s3 storage with bucket and region.
///
/// # Errors
///
/// When could not initialize the client instance
pub fn new(bucket_name: &str, region: &str) -> Result<Store> {
    let s3 = AmazonS3Builder::new()
        .with_bucket_name(bucket_name)
        .with_region(region)
        .build()
        .map_err(Box::from)?;

    Ok(Store::new((Box::new(s3) as Box<dyn ObjectStore>).into()))
}
```

**Comment by fan-tastic-z** [comment]
> currently, no; you can see the AWS builders [here](https://github.com/loco-rs/loco/blob/master/src/storage/drivers/aws.rs).
> 
> Why are you not working in-mem driver in development?

ok, I use minio, because api upload file store minio, other service will use file by minio.

**Comment by daflyinbed** [comment]
Is it possible to add an api or re-export the AmazonS3Builder? I'm working with another cloud provider's object storage which are compatible with S3 api.

**Comment by magj2006** [comment]
> > currently, no; you can see the AWS builders [here](https://github.com/loco-rs/loco/blob/master/src/storage/drivers/aws.rs).
> > Why are you not working in-mem driver in development?
> 
> ok, I use minio, because api upload file store minio, other service will use file by minio. I would like to use object_store to communicate with my local object store (which is a minio object store) I initialize the client like this
> 
> ```
> let s3 = AmazonS3Builder::new()
>     .with_endpoint("http://localhost:30002")
>     .with_region("us-east-1") // Dummy region for local testing
>     .with_bucket_name("my-bucket")
>     .with_access_key_id("minio")
>     .with_secret_access_key("miniostorage")
>     .build()
>     .expect("error creating s3");
> ```

Hey, does it work if use minio now ?  what to do if use minio ?

**Comment by fan-tastic-z** [comment]
> > > currently, no; you can see the AWS builders [here](https://github.com/loco-rs/loco/blob/master/src/storage/drivers/aws.rs).
> > > Why are you not working in-mem driver in development?
> > 
> > 
> > ok, I use minio, because api upload file store minio, other service will use file by minio. I would like to use object_store to communicate with my local object store (which is a minio object store) I initialize the client like this
> > ```
> > let s3 = AmazonS3Builder::new()
> >     .with_endpoint("http://localhost:30002")
> >     .with_region("us-east-1") // Dummy region for local testing
> >     .with_bucket_name("my-bucket")
> >     .with_access_key_id("minio")
> >     .with_secret_access_key("miniostorage")
> >     .build()
> >     .expect("error creating s3");
> > ```
> 
> Hey, does it work if use minio now ? what to do if use minio ? @fan-tastic-z

I didn’t have the author’s idea at the time, and I still couldn’t use it at the time

**Comment by magj2006** [comment]
> > > > currently, no; you can see the AWS builders [here](https://github.com/loco-rs/loco/blob/master/src/storage/drivers/aws.rs).
> > > > Why are you not working in-mem driver in development?
> > > 
> > > 
> > > ok, I use minio, because api upload file store minio, other service will use file by minio. I would like to use object_store to communicate with my local object store (which is a minio object store) I initialize the client like this
> > > ```
> > > let s3 = AmazonS3Builder::new()
> > >     .with_endpoint("http://localhost:30002")
> > >     .with_region("us-east-1") // Dummy region for local testing
> > >     .with_bucket_name("my-bucket")
> > >     .with_access_key_id("minio")
> > >     .with_secret_access_key("miniostorage")
> > >     .build()
> > >     .expect("error creating s3");
> > > ```
> > 
> > 
> > Hey, does it work if use minio now ? what to do if use minio ? @fan-tastic-z
> 
> I didn’t have the author’s idea at the time, and I still couldn’t use it at the time

Did you try to use http or local ?
