### ISSUE TITLE
loco model schema data types error

### ISSUE THREAD

**Issue by fan-tastic-z** [loco-rs/loco#455]
**Description**
 
Currently, SeaORM in loco has been upgraded to 1.0.0-rc.1, and `use sea_orm_migration::schema::**` is used in migrations.
But when loco generates model, schem data type uses the old schema in loco, such as:
```
("bool", "bool_null"),
("bool!", "bool"),
("jsonb", "jsonb_null"),
("jsonb!", "jsonb"),
```
This will cause errors in the generated migration
The corresponding one in SeaORM should be：
```
pub fn boolean<T: IntoIden>(col: T) -> ColumnDef {
    boolean_null(col).not_null().take()
}

pub fn boolean_null<T: IntoIden>(col: T) -> ColumnDef {
    ColumnDef::new(col).boolean().take()
}
pub fn json_binary<T: IntoIden>(col: T) -> ColumnDef {
    json_binary_null(col).not_null().take()
}

pub fn json_binary_null<T: IntoIden>(col: T) -> ColumnDef {
    ColumnDef::new(col).json_binary().take()
}
```

So it should be
```
boolean->boolean_null
boolean!->boolean
jsonb -> json_binary_null
jsonb!->json_binary
```

The uuid_col and uuid_col_null originally used in loco also need to be adjusted.

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z, do you want to open PR with this fix?

OK，I enjoyed doing it so much I tried to fix it

**Comment by kaplanelad** [comment]
@fan-tastic-z will be released in the next version

**Comment by fan-tastic-z** [comment]
> @fan-tastic-z will be released in the next version

Ok
