### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by silicakes** [loco-rs/loco#47]
Add contribution guidelines, including explanation about labeling and steps for getting your first PR merged into the project.

Here's an example which isn't too "official" and properly helps with contributing.

https://github.com/zellij-org/zellij/blob/main/CONTRIBUTING.md

**Comment by jondot** [comment]
Yep. will do,
We're still closing out the last details of what makes `loco` into a first version, by the way. We'd really love contributions.

BTW would you mind sharing how did you hear about this project?

**Comment by silicakes** [comment]
Great to hear!
I've been hanging out on the discord server where you guys were talking about it.
Would also love to contribute however I can!:)

**Comment by jondot** [comment]
Fantastic, we'll get close to a first version and ping you
`CONTRIBUTING.md` - added!
