### ISSUE TITLE
Response does not included body content from loco::Error::BadRequest, loco::Error::Message and more

### ISSUE THREAD

**Issue by yinho999** [loco-rs/loco#495]
**Description**
All the Error responses except listed ones is set to status code 400 with a body "BadRequest". This means body content in loco::Error::BadRequest, loco::Error::Message are not display nor returned.

![image](https://github.com/loco-rs/loco/assets/26657530/ef03dcd1-17ed-412f-8a51-1fef2b89be5e)

**Comment by yinho999** [comment]
@jondot Would you mind assigning this ticket to me, please? Thanks!

**Comment by schungx** [comment]
I suggest adding the ability to return response in any format, not just JSON...  

Best it is for user to be able to trap this and return whatever he/she wants...

**Comment by jondot** [comment]
yep myself and @kaplanelad  just bumped into this a week ago at a design session. we had a first sketch for a general solution, we'll try to create a draft for it in code

**Comment by jondot** [comment]
After today's session, we realized this is almost perfectly solved with the new `Responses` refactor. 
Check this out https://github.com/loco-rs/loco/commit/3daa7c8e16be1d43abaea5dc1314f1d536d27a9c#diff-0b15761e9ed044c881df8e964d0354ba15700c942dd3ff6f78a638b590b0340c

**Comment by yinho999** [comment]
> After today's session, we realized this is almost perfectly solved with the new `Responses` refactor. Check this out [3daa7c8#diff-0b15761e9ed044c881df8e964d0354ba15700c942dd3ff6f78a638b590b0340c](https://github.com/loco-rs/loco/commit/3daa7c8e16be1d43abaea5dc1314f1d536d27a9c#diff-0b15761e9ed044c881df8e964d0354ba15700c942dd3ff6f78a638b590b0340c)

LGTM!
