### ISSUE TITLE
App banner, information, on start up

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#5]
Enhance the booting process logging for the application by including detailed information such as server IP, relevant context, server mode, etc. This includes printing:

Loaded middlewares.
Current environment details.
Available routes.
Additional relevant information.

These improvements aim to make the bootstrap logger more visually appealing and informative.

**Comment by jondot** [comment]
use colors and icons appropriately

```
[ banner ]

environment: development
logger: debug
database: automigrate, truncate, recreate, logging
middleware: logger, limit_payload
mode: server | server-and-worker | worker

server listening on port: 3000
```


worker

```
[ banner ]

environment: development
logger: debug
database: automigrate, truncate, recreate, logging
mode: worker

worker online
```
