### ISSUE TITLE
bug: cargo error: no such command: `loco`

### ISSUE THREAD

**Issue by silicakes** [loco-rs/loco#50]
**Description**

When following the [tutorial](https://loco.rs/docs/getting-started/tour/), running `cargo loco run` I'm getting the following error:

```sh
$ cargo loco run
error: no such command: `loco`

        Did you mean `doc`?

        View all installed commands with `cargo --list`
(base)
```

Additional information:
Project was generated with `loco new`
cwd =  generated folder

**Comment by kaplanelad** [comment]
Should work now. please try again

**Comment by silicakes** [comment]
Solved, thanks!
