### ISSUE TITLE
Cargo tests fails without features option

### ISSUE THREAD

**Issue by clefelhocz2** [loco-rs/loco#504]
**Description**

I was hoping i might contribute to loco.   I did a generic clone of the loco repo and cargo test just to get things setup.  When I did this, the cargo test failed in the doc-tests:

```
failures:

---- src/controller/mod.rs - controller (line 9) stdout ----
error[E0432]: unresolved import `loco_rs::controller::channels`
  --> src/controller/mod.rs:16:17
   |
10 |    controller::{channels::AppChannels, AppRoutes},
   |                 ^^^^^^^^ could not find `channels` in `controller`

error[E0407]: method `register_channels` is not a member of trait `Hooks`
  --> src/controller/mod.rs:53:4
   |
47 | /    fn register_channels(_ctx: &AppContext) -> AppChannels {
48 | |        let channels = AppChannels::default();
49 | |        //channels.register.ns("/", channels::application::on_connect);
50 | |        channels
51 | |    }
   | |____^ not a member of trait `Hooks`
```
Running with --features channels succeeds.  It seems like we should either have channels be dependency or make the code in mod.rs variable on the channells feature.  

**To Reproduce**

Clean repo with cargo build then cargo test.  

**Expected Behavior**

All tests pass.  

**Environment:**

**Additional Context**

Let me know if I'm doing something wrong here.   If not, guidance on which way to go would be help guide me to a submit a PR to resolve this.   Also any suggested issues to start with would be appreciated.  I was looking at #372 as an example.

**Comment by kaplanelad** [comment]
https://github.com/loco-rs/loco/pull/624

**Comment by kaplanelad** [comment]
Thanks @clefelhocz2. 
This issue fixed the the pr: https://github.com/loco-rs/loco/pull/624
