### ISSUE TITLE
conflict with registered route: /_ping

### ISSUE THREAD

**Issue by erhards0812** [loco-rs/loco#517]
**Description**

When setting a route to / for a landing page, I get the following error

```
.cargo/registry/src/index.crates.io-6f17d22bba15001f/axum-0.7.4/src/routing/mod.rs:218:13:
Invalid route "/": insertion failed due to conflict with previously registered route: /_ping
```

The culprit seems to be in loco-rs-0.3.1/src/controller/ping.rs

**To Reproduce**

set a route to /

``` rust

pub async fn hello(ViewEngine(v): ViewEngine<TeraView>) -> Result<impl IntoResponse> {
    crate::views::home::home(v)
}

pub fn routes() -> Routes {
    Routes::new()
        .add("/", get(hello))
}

```

**Expected Behavior**

Be able to set a route to / for showing a landing page

**Environment:**

**Comment by jondot** [comment]
can you please upload a working reproduction of this to some public repo so I can try to experience this myself?

**Comment by kaplanelad** [comment]
@erhards0812 I'm closing this issue. If you still have a problem, feel free to reopen it or create a new one.
