### ISSUE TITLE
Replace Redis with Valkey (or other alternatives)

### ISSUE THREAD

**Issue by simonsan** [loco-rs/loco#520]
Due to recent license changes, it may hinder adoption of loco, that it pulls in Redis in its SaaS template, maybe a change to Valkey could be useful?

See https://www.theregister.com/2024/04/03/open_source_redis_alternative/

**Comment by jondot** [comment]
I believe most of this would be docs changes, right?

**Comment by Muxoid** [comment]
I created a pull request if this is the direction that the project wants to take, [the pull request](https://github.com/loco-rs/loco/pull/523).
