### ISSUE TITLE
suggestion: Add a deployment doument entry

### ISSUE THREAD

**Issue by silicakes** [loco-rs/loco#53]
Hi everyone,

I'm a strong proponent of WIX's "nothing to deploy" philosophy which states that the first thing you do is, well - deploy!:)

I'd love to see some common ways of creating a CI/CD around loco and even deploying it manually.

We can consider giving examples for popular tier 2 providers such as digital ocean, linode, heroku and others and perhaps even providing some common steps to automate deployments for aws/azure/gcp.

(putting a small pin here for openshift/rancher)

Since deploying is basically running your binary somewhere, it could be a great article / doc entry with actual examples showing how it's mostly the same for everything.

I'd also like to discuss whether a "deploy first" approach is something we wish to adopt and thus - start every tutorial with this step.

**Comment by jondot** [comment]
yea you nailed it, because we only ship a binary + folder with tiered configuration files:

```
your-service-bin       <-----      ~20MB binary
config/
   development.yaml        <----- keep only the files you need (In production, keep only 'production.yaml')
   testing.yaml
   production.yaml
```

if you're feeling brave and want to give it a try, we can mentor you through building an app

**Comment by jondot** [comment]
@silicakes I've added a trivial entry here:

https://loco.rs/docs/getting-started/deployment/

Feel free to open a PR with additions if you have ❤️
