### ISSUE TITLE
loco-cli doesn't have the subcommand "generate"

### ISSUE THREAD

**Issue by dev-ardi** [loco-rs/loco#534]
```
$ loco --help
loco cli website generator

Usage: loco [OPTIONS] <COMMAND>

Commands:
  new   Create a new Loco website
  help  Print this message or the help of the given subcommand(s)

Options:
  -v, --verbose...  Verbosity level
  -h, --help        Print help
  -V, --version     Print version
```
```
$ loco --version
loco-cli 0.2.6
```
It doesn't have the `generate` subcommand in the docs https://loco.rs/docs/getting-started/deployment/#generate

```
$ loco generate
error: unrecognized subcommand 'generate'

Usage: loco [OPTIONS] <COMMAND>

For more information, try '--help'.
```

**Comment by jondot** [comment]
Correct, use the `loco-cli` to initialize a new project. Then, go in the project and run `cargo loco generate ...` to have generators.

The docs state `cargo loco generate deployment` and assume you're inside your active project.

Thanks for reporting this -- I encourage you to keep reporting odd stuff, we learn from each report.

**Comment by dev-ardi** [comment]
Oh it's a bit odd to have both `loco` and `cargo loco` do different stuff :P
