### ISSUE TITLE
"ActiveCache" subsystem for streamlined cache service in Loco

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#541]
The next major subsystem in Loco would be something like ActiveCache/ActionCache, where a cache is available as part of the context.

For various use cases:

* data caching of specific records
* alleviating N+1 with cache
* caching complete responses for super fast APIs (e.g. caching inference responses)
* caching data for multi-step compute in workers / jobs
* ability to work completely in-memory for the cache, supporting cases like lightweight services, with no Redis at all
* and more..

# Initial braindump

* [ ] find some nice inmem rust cache, compact, that can store serializeable and can evacuate, monitor memory, etc. (is there already a mega multi-provider cache lib in Rust?)
* [ ] points to verify:
  * write-thru
  * store values, strings
  * handling of lists n->many, relations
  * shaping local structure data into a cache entry
  * get a single item and a list, (maybe also get a glob?)
   - expiry
   - scavenger (task, or periodic)
   - cache monitoring and reports, hit/miss
   - global flag to work without cache (transparent / test mode)
   - central entry expiry control via config
   - different providers, local inmem, redis(from context or external), all watching memory size
   - emphasis on local vs global cache (i.e cache local to: request, machine, or global cache that's shared with all machines and all requests across a network)
     
* Some Rails background:
  * https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-store 
     

```ruby
   class Product < ApplicationRecord
      def competing_price
         Rails.cache.fetch("#{cache_key_with_version}/competing_price", expires_in: 12.hours) do
            Competitor::API.find_price(id)
         end
      end
   end
```

* [ ] move workers to their own Redis configuration definition, because a global Redis is no longer the correct abstraction. However since the worker library we use needs an external Redis, rename `AppContext.redis` to `AppContext.queue` and then let the processor subframework take that. The original idea was "yea, what if we just need a Redis for general purpose things -- let's reuse the existing Redis that's used for queues" can now be sunset upon introduction of the new cache subsystem. In terms of _minimalism_ we can still use the same Redis server, giving 2 configuration urls that are identical to both the queue and cache subsystem, or pick an in-memory cache if we'd like (cache will be local to the machine).
* [ ] meanwhile, establish `AppContext.cache` as the entry point for the cache subsystem

**Comment by kaplanelad** [comment]
https://github.com/loco-rs/loco/pull/570
