### ISSUE TITLE
Getting Started section of guide has commands that do not work as expected

### ISSUE THREAD

**Issue by trevoranderson** [loco-rs/loco#552]
**Description**

Output of some steps does not match the guide. It appears like all routes are hitting the fallback endpoint and returning the index.html?

```
$ curl localhost:3000/api/_ping
{"ok":true}
```

but actual result was

```
$ curl localhost:3000/api/_ping
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/x-icon" href="/assets/favicon-WRxYIZSq.ico">
    <title>Loco SaaS Starter</title>
    <script type="module" crossorigin src="/assets/index-9xajtB06.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-NNfN60X4.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
```

**To Reproduce**

Follow the guide at https://loco.rs/docs/getting-started/guide/
after starting the server and observing the output
```
                      ▄     ▀                     
                                 ▀  ▄             
                  ▄       ▀     ▄  ▄ ▄▀           
                                    ▄ ▀▄▄         
                        ▄     ▀    ▀  ▀▄▀█▄       
                                          ▀█▄     
▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄   ▄▄▄▄▄▄▄▄▄▄▄ ▄▄▄▄▄▄▄▄▄ ▀▀█    
 ██████  █████   ███ █████   ███ █████   ███ ▀█   
 ██████  █████   ███ █████   ▀▀▀ █████   ███ ▄█▄  
 ██████  █████   ███ █████       █████   ███ ████▄
 ██████  █████   ███ █████   ▄▄▄ █████   ███ █████
 ██████  █████   ███  ████   ███ █████   ███ ████▀
   ▀▀▀██▄ ▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀ ██▀  
       ▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀    
                https://loco.rs

environment: development
   database: automigrate
     logger: debug
compilation: debug
      modes: server

listening on [::]:3000
```

run `curl localhost:3000/api/_ping` as specified in the guide

**Expected Behavior**

Output should match what the guide says

**Environment:**
macOS Sonoma 14.4.1
All loco setup steps run on April 22, 2024
rustc 1.77.2 (25ef9e3d8 2024-04-09)

**Additional Context**
`curl localhost:3000/api/_health` has a similar issue

later in the guide, the given home.rs does not compile with error
```
home.rs:6:5
  |
5 | async fn hello(State(_ctx): State<AppContext>) -> Result<String> {
  |                                                   -------------- expected `std::result::Result<std::string::String, loco_rs::Error>` because of return type
6 |     format::text("ola, mundo")
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<String, Error>`, found `Result<Response<Body>, Error>`
  |
  = note: expected enum `std::result::Result<std::string::String, _>`
             found enum `std::result::Result<axum::http::Response<Body>, _>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile
```
curling nonexistent routes returns the same result

**Comment by trevoranderson** [comment]
After some investigation, it seems to be because the curl routes given by the guide do not match the configuration
`curl localhost:3000/_ping ` works, the leading `api` prefix in the guide is incorrect.

**Comment by trevoranderson** [comment]
More issues I came across reading the guide

Every new build causes a Mac firewall popup because it is listening on default interface and not explicitly localhost.
Fixable by editing loco's `cli.rs`
````
            let serve_params = ServeParams {
                port: port.map_or(boot_result.app_context.config.server.port, |p| p),
                binding: binding.map_or(
                    "localhost".to_string(),
                    |b| b,
                ),
            };
````
A separate issue involves playground
In the `Using playground to interact with the database` section
````
Error: playground

Caused by:
    no configuration file found
````
This happens if you have a different workspace structure (mine is at a higher level and the loco app's `Cargo.toml` is ordinary crate).  It looks for items from the workspace level and then doesn't find it because they are actually at the crate level. A similar thing happens inside the `mailers/auth.rs` file in the `include_dir!` invocations. I fixed this one by running the cargo commands from the crate working directory instead of the workspace root.

A compile error in the sample code of `Building a CRUD API`. Replacing `format::empty()` with `Ok(())` seems to fix it.

At the `Add a new article:` the route is shown as `localhost:3000/api/articles` but should be `localhost:3000/articles`

Some of the `cargo loco generate` commands have scary warnings about needing nightly. A sampling
````
Warning: can't set `wrap_comments = true`, unstable features are only available in nightly channel.
Warning: can't set `comment_width = 80`, unstable features are only available in nightly channel.
Warning: can't set `format_strings = true`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
````

The `user_report` task is not generated for you as the guide suggests. If you add the file, and work through the compile erorrs, it is still not runnable. You have to run the `cargo loco generate task user_report`, but if the task file is already there it will not add it to the task list shown when you run `cargo loco task` and you will not be able to run it. It seems odd that this is the case- shouldn't it continue wiring up the task if the file was already created?

**Comment by trevoranderson** [comment]
`let boot = testing::boot_test::<App>().await.unwrap();`
Most of the generated sample tests are failing at this line. The bootstrapped environment returns an error object then it's unwrapped. Here's some error output
```
called `Result::unwrap()` on an `Err` value: DB(Conn(SqlxError(Database(PgDatabaseError { severity: Fatal, code: "28P01", message: "password authentication failed for user \"trevor\"", detail: None, hint: None, position: None, where: None, schema: None, table: None, column: None, data_type: None, constraint: None, file: Some("auth.c"), line: Some(326), routine: Some("auth_failed") }))))

```

**Comment by jondot** [comment]
I just fixed `big_int` and the docs regarding `/ping` are now OK.
I'd be happy to get a summary of remaining issues in this thread?
