### ISSUE TITLE
Add information section to documentation about order of extractors mattering

### ISSUE THREAD

**Issue by isaacdonaldson** [loco-rs/loco#567]
**Description**

In the `axum` create, the order of the extractors in the handler params are quite important, and to people unfamiliar with axum it could be quite confusing as to why their code is not compiling. 

Adding an information section disclaimer that order of extractors matter and linking to the [relevant documentation](https://docs.rs/axum/latest/axum/extract/index.html#the-order-of-extractors) could be a big help.

As well as adding information about adding the [`#[debug_handler]`](https://docs.rs/axum-macros/latest/axum_macros/attr.debug_handler.html) macro to improve handler error messages.

Relevant issue: https://github.com/loco-rs/loco/issues/558

**Comment by isaacdonaldson** [comment]
I should've looked at the documentation more closely, I see that order being important is mentioned.

Maybe add a link to the documentation?

I still think mentioning something about `#[debug_handler]` is useful

**Comment by schungx** [comment]
Agree.

The worse thing is: the error messages are absolutely no help at all.  Unfortunately that seems to be a problem with many Rust crates dependent on the generics system.

**Comment by kaplanelad** [comment]
@isaacdonaldson, we accept pr :) you are more than welcome to open us pr and document it in [loco.rs](https://github.com/loco-rs/loco/tree/master/docs-site/content/docs) docs.

The `#[debug_handler]` was merged
