### ISSUE TITLE
Configurable Auth Token Location.

### ISSUE THREAD

**Issue by Muxoid** [loco-rs/loco#579]
**Description**

I would like to be able to use cookies for authenticating instead of having a plain header so that it is sent automatically with each request. This would be made easier with a request like this:

curl --location --request GET '127.0.0.1:3000/api/user/current' \
     --header 'Content-Type: application/json' \
     --Cookie 'Authorization=Bearer TOKEN'

instead of the current:

curl --location --request GET '127.0.0.1:3000/api/user/current' \
     --header 'Content-Type: application/json' \
     --header 'Authorization: Bearer TOKEN'

At the moment there is no easy way to customize this.

**Expected Behavior**

To be able to use cookies to authenticate to be able to simplify the client-side authentication logic.  Making this a config option would make the framework more flexible.

**Additional Context**

I am currently working with Loco and HTMX, therefore I render simple pages and I would like to use the built-in authentication methods without client-side JS.

**Comment by kaplanelad** [comment]
Hey @Muxoid

In the next release version, we will add this option. 
In the meantime, you can take the lib from git, and you will get this feature.

for more info take a look on this pr:
You can can follow this [PR](https://github.com/loco-rs/loco/pull/560/files).

**Comment by kaplanelad** [comment]
@Muxoid new version releases with this feature. 
You can follow the guide [here](https://loco.rs/docs/the-app/controller/#middleware).
