### ISSUE TITLE
Move away from default port of `3000` to `5150`

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#600]
In order to avoid the over-used over-popular port of 3000 and avoid collisions of ports, cookies, sessions and app data, we suggest moving to [5150](https://en.wikipedia.org/wiki/5150_(album)).

Also make sure `cargo loco start -p custom-port` works smooth and flawless if anyone wants to keep `3000`

**Comment by dinosath** [comment]
can you assign it to me?

**Comment by jondot** [comment]
Sure done, 
A few pointers:
* In addition for looking for the port in code, take a look at the CI jobs
* If you find any `3000` number in the wild which is not in a constant, try to refactor it into a constant
* the documentation probably will have a bit of changes, so mind those as well. we use a new tool @kaplanelad  developed for code snippets and code chunks called `snipdoc` (see its [configuration](https://github.com/loco-rs/loco/blob/master/snipdoc.yml)), see [how to install and use here](https://github.com/loco-rs/loco/blob/master/.github/workflows/docs.yml#L30)
