### ISSUE TITLE
 Any new Project with Sass or Rest template fails to build

### ISSUE THREAD

**Issue by brahimABD98** [loco-rs/loco#606]
**Description**

Any fresh new Project  (made with the Sass or Rest template)  fails to build with error message 
```sh
error: could not compile `time` (lib) due to 1 previous error
error[E0282]: type annotations needed for `Box<_>` \.cargo\registry\src\index.crates.io-6f17d22bba15001f\time-0.3.34\src\format_description\parse\mod.rs:83:9

let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
```

**To Reproduce**
Setup a new project using the Sass template and run cargo build or cargo run 

**Expected Behavior**

the project should build

**Environment:**
Windows 11
**Additional Context**
the error happens inside the dev container too so it's not windows related

**Comment by jondot** [comment]
This is strange, we have a CI job that generates and builds a project for each of those. Can you take a look at the CI job and see what the difference is from what you're trying to do?

**Comment by kaplanelad** [comment]
@brahimABD98, can you now try the latest nightly version?

**Comment by brahimABD98** [comment]
@kaplanelad works perfectly
