### ISSUE TITLE
Magic link auth

### ISSUE THREAD

**Issue by askasp** [loco-rs/loco#613]
You have already made a email verification for password login, is it a great endeavour to have an option for "no-password", that is only magic links?

**Comment by jondot** [comment]
I think it may be a great idea - I believe all the pieces are here for it.

If you want to create a draft of how the developer experience will be, we'll be happy to help you submit a PR for it.

**Comment by kaplanelad** [comment]
- create a new col under user model: magic_token, magic_token_expeired (2 min)
- create post endpoint `atuh_magic_link` and get user email
- Send the magic link in an email
- When click on the link generate jwt token
