### ISSUE TITLE
Renaming crate to loco from loco-rs

### ISSUE THREAD

**Issue by ijsnow** [loco-rs/loco#621]
**Description**

I'd like to suggest renaming the crate from `loco-rs` to `loco`. The primary concern would be a supply chain vulnerability. I know the intent is for everything to be installed through the loco cli, but it would be natural for someone to try to install a framework called `loco` by running `cargo install loco` instead of `cargo install loco-rs`. Right now, there is no crate names `loco`, meaning that a nefarious actor could quietly snag that and install malicious code on a target's system. 

If this org snags the crate name just to prevent that but leaves the name how it is on crates.io, I'd like to ask why you insist on making us type `_rs` in a `.rs` file? We know we are righting rust :) Its a common convention to have a repo or org on github with the suffix `(-|_)rs` but not for the crate itself to have the suffix.

**Comment by kaplanelad** [comment]
When @jondot and i started this project, I remember that `loco` crate was taken. This is why we added `-rs` to the crate name.

But you shouldn't install loco with the command `cargo install loco-rs`. This is the lib. You need to run `cargo install loco-cli`, and the CLI creates the project with the `loco-rs` crate.

**Comment by jondot** [comment]
Closing this as we're going to rename the CLI to just `loco`. thanks @ijsnow
