### ISSUE TITLE
Is graphql supported in the future?

### ISSUE THREAD

**Issue by RustLoverTheCoder** [loco-rs/loco#622]
Is graphql supported in the future?

**Comment by kaplanelad** [comment]
Can you elaborate?

**Comment by kaplanelad** [comment]
yes it supported.

I'll open them a pr with working example

**Comment by kaplanelad** [comment]
@RustLoverTheCoder I have created a working example. you can take a look here:
https://github.com/async-graphql/examples/pull/87
