### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by BWStearns** [loco-rs/loco#632]
## Feature Request

I find it really helpful to have SwaggerUI for my APIs. It especially helps for working with frontend devs who might not speak Rust.

[`Utopia-swagger-ui`](https://github.com/juhaku/utoipa) looks like a good option and they already have an Axum integration so it seems like a 

There are other swagger-ui implementations in Rust but Utopia looks like the closest to a drop-in solution.

Related issue #612.

**Comment by shakhzodkudratov** [comment]
Hello, I'm also doing a research in this field. Try to use [poem](https://github.com/poem-web/poem) with its built-in openapi support. It is a pleasure to me after utoipa, where you need to manually wire utoipa itself separately and type every parameter, property. utoipa is unsound, it doesn't make checks and lies (mostly because you forgot to fix some routes)

**Comment by Heiss** [comment]
> Hello, I'm also doing a research in this field. Try to use [poem](https://github.com/poem-web/poem) with its built-in openapi support. It is a pleasure to me after utoipa, where you need to manually wire utoipa itself separately and type every parameter, property. utoipa is unsound, it doesn't make checks and lies (mostly because you forgot to fix some routes)

Maybe should give [aide](https://github.com/tamasfe/aide) a try. I do not have time to test it with loco right now, but was discussed in [axum issues](https://github.com/tokio-rs/axum/issues/50#issuecomment-1590214312) already. The examples seems very promissing to me.

**Comment by depth-liu** [comment]
[salvo](https://github.com/salvo-rs/salvo) is another good alternative with very nice OpenAPI integration and is simple to use.

**Comment by jondot** [comment]
We are now concluding this with https://github.com/loco-rs/loco/tree/master/examples/demo#openapi-with-utoipa
If anyone wants to work on a PR that gets the "holy grail" of deriving a spec from a live API, we'll be happy to look at it (see more here: https://github.com/loco-rs/loco/issues/778)

**Comment by stan-dot** [comment]
@jondot the link does not work at the moment

**Comment by kaplanelad** [comment]
Please follow this repo: [loco-rs/loco-openapi-initializer](https://github.com/loco-rs/loco-openapi-Initializer).
We’ve moved it to become the Loco Initializer.
