### ISSUE TITLE
Add example using `utoipa` for OpenAPI spec (in examples/demo)

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#640]
See https://github.com/huggingface/text-generation-inference/blob/main/router/src/server.rs#L1438 

related issues: 

- [ ] add example
- [ ] add a new readme mapping a topic to specific code (direct link)

* https://github.com/loco-rs/loco/issues/632 
* https://github.com/loco-rs/loco/issues/612

**Comment by jondot** [comment]
done https://github.com/loco-rs/loco/tree/master/examples/demo#openapi-with-utoipa

**Comment by mandarvaze** [comment]
Above link is 404  as of now
I could not find the details in official documentation either @jondot

**Comment by ekivolowitz** [comment]
@mandarvaze I was able to find the example that @jondot referenced with `git grep`. I'm new to rust and loco and am trying to set up utoipa myself. If you get it figured out, please let me know and I'll do the same.

https://github.com/loco-rs/loco/tree/75513b641bfca4fbef86e2ae9258c9ae551d6a8d/examples/demo
