### ISSUE TITLE
Add ability to provide fallback handler to AppRoutes

### ISSUE THREAD

**Issue by swlody** [loco-rs/loco#643]
## Feature Request

Currently, `controller::AppRoutes::to_router()` constructs an `axum::Router` with no fallback function. This means that it is not possible to have e.g. a custom 404 handler. It is possible to get around this by implementing `Hooks::after_routes()` and calling `Router::fallback()` on the provided `axum::Router`. However, the `after_routes()` callback is initiated after `AppRoutes::to_router()` is called https://github.com/loco-rs/loco/blob/7b716a73bf602c9a0aec95b0c72ac42791cf6305/src/boot.rs#L268-L269. This means that any middleware that was added is not provided to the fallback handler.

**Describe the solution you'd like**

Add a `add_fallback(fallback: Handler)` method to `controller::AppRoutes` so that a fallback handler can be added to the `axum::Router` and have all the relevant middleware applied to it.

This is potentially difficult to achieve since `axum::Router::fallback()` accepts an `axum::handler::Handler<T, S>` so `AppRoutes` would also need to be templated on `<T, S>` to be able to store the fallback on it.

**Describe alternatives you've considered**

Alternate solution is to move the call to `after_routes()` into `controller::AppRoutes::to_router()` so that it is actually applied immediately after the routes are registered. https://github.com/loco-rs/loco/blob/7b716a73bf602c9a0aec95b0c72ac42791cf6305/src/controller/app_routes.rs#L184-L190

This is however a potentially breaking change. Another problem with this method is that it would separate the location where `Hooks::after_routes()` is called from the location where `Initializer::after_routes()` is called. Also, `AppRoutes::to_router()` is not an async function while `Hooks::after_routes()` is (why?).

**Comment by kaplanelad** [comment]
@swlod, 
you can use `after_routes` hook, which gets the axum router. 
this is the place you can add the fallback custom function

**Comment by swlody** [comment]
> @swlod, you can use `after_routes` hook, which gets the axum router. this is the place you can add the fallback custom function

Maybe I'm missing something here. The problem that I am having using after_routes is that any fallback added in this function doesn't have any of the default middleware applied to it because it is called after the middleware is added to the router.

**Comment by swlody** [comment]
Two related potential solutions:

Provide `Hooks::before_routes()` for the user to implement. Called after the initializers and before the router is created. The signature would look like this:

```rust
async fn before_routes(
    router: axum::Router<AppContext>,
    _ctx: &AppContext,
) -> Result<axum::Router<AppContext>> {
    Ok(router.fallback(fallback_handler))
}
```

The router would then be passed to `AppRoutes::to_router()` instead of the router being created inside that function. This would allow the user to add whatever they want to the router and still have it be affected by the loco middleware.

Example implementation for the user:

```rust
async fn before_routes(
    router: axum::Router<AppContext>,
    _ctx: &AppContext,
) -> Result<axum::Router<AppContext>> {
    Ok(router.fallback(fallback_handler))
}
```

Modification to `AppRoutes::to_router()` prototype:

```rust
pub fn to_router(
    &self,
    ctx: AppContext,
    mut app: axum::Router<AppContext>,
) -> Result<AXRouter>
```

Change to boot.rs `run_app()`:

```rust
let router = Router::<AppContext>::new();
let router = H::before_routes(router, &app_context).await?;
let app = H::routes(&app_context).to_router(app_context.clone(), router)?;
```


Related (cleaner?) solution is to add a new function to `Hooks`: `router()`. Similar to above, the user will be expected to "seed" the router by returning a router from this function. In Hooks:

```rust
fn router(_ctx: &AppContext) -> Result<AxumRouter>;
```

In boot.rs:

```rust
// Old:
let app = H::routes(&app_context).to_router(app_context.clone())?;
// New:
let app = H::router(&app_context)?;
```

In AppRoutes:

```rust
pub fn to_router(
    &self,
    ctx: AppContext,
    initial_router: axum::Router<AppContext>,
) -> Result<AXRouter> {
    let mut app = initial_router;
...
}
```

User implementation:

```rust
fn router(ctx: &AppContext) -> Result<Router> {
    let router = Router::new().fallback(fallback_handler);
    let router = Self::routes(ctx).to_router(ctx.clone(), router)?;
    Ok(router)
}
```
