### ISSUE TITLE
"health check" while starting up

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#68]
context: https://github.com/loco-rs/loco/issues/65

what can help is create a health check (similar to the `_health` endpoint), that:

* fails fast
* reports what is wrong (db connection missing, or redis missing)
* provides a next step inline (shows what's configured right now in the database, and recommends what to configure or what to run, eg. command to run postgres in a docker container)
* provides a link to docs for the relevant section (not a specific thing since docs might change and break, just to the top-level section)

## Checks

[ ] postgres (connection ok)
[ ] redis (connection ok)
[ ] seaorm cli (for migration) -- this is a thinker. in development, we want seaorm cli for sure. in production, it's not so certain. on one hand, we might want to run migrations on production when starting up, or when issuing an external command, **but on the other hand** some teams would prefer to run migrations from a "blessed" workstation connecting to production postgres. @kaplanelad WDYT?

**Comment by kaplanelad** [comment]
**Postgress**:
We have a timeout configuration for PostgreSQL, ensuring that connectivity fails quickly (depending on the specified timeout).
don't you think it is enough?

**Redis**:
Do you believe it's advisable to halt the server, or would it be more appropriate to display a message? i see some cases that Redis can be down, and you still want the webserver is run

**Seaorm cli:**
We can prompt a message that `seorm-cli` is not installed / not in the same version we expect. i wrote it in issue #82

**Comment by jondot** [comment]
after reading what you're saying, and thinking about it more, I think we should have something like this:

```sh
$ cargo loco doctor
✅ SeaORM CLI is installed
✅ Postgres connection: success
✅ Redis connection: success
```

```sh
$ cargo loco doctor
⚠️ SeaORM CLI was not found
To fix, run:
      $ cargo install sea-orm-cli

✅ Postgres connection: success
✅ Redis connection: success
```
Kind of: run a vector of checks. each check has a recommended fix.

**Comment by kaplanelad** [comment]
Yes, this is much better. We just need to ensure that if there is an issue with one of our checkers, we shouldn't exit with 0.
