### ISSUE TITLE
mysql problem

### ISSUE THREAD

**Issue by lgfinfo** [loco-rs/loco#681]
**Description**
when i use mysqldb something hanppend:
cargo loco generate model candidate title:string! description:string platform:json extra_data:json image:string election:references user:references

   --> src/models/users.rs:259:52
    |
259 |         self.reset_sent_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                               ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `DateTime<Utc>`, found `NaiveDateTime`
    |                                               |
    |                                               arguments to this enum variant are incorrect
    |

**Comment by kaplanelad** [comment]
Hi @lgfinfo,
We've made some changes in this area. Could you please test against the `sqlite-seaorm-v1` branch and let us know if it works?

Thanks!

**Comment by kaplanelad** [comment]
@lgfinfo  should fix in version 0.7.0.
