### ISSUE TITLE
issues after creating new model

### ISSUE THREAD

**Issue by nowfalsalahudeen** [loco-rs/loco#683]
error[E0308]: mismatched types
   --> src/models/users.rs:241:65
    |
241 |         self.email_verification_sent_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                                            ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Vec<u8>`, found `NaiveDateTime`
    |                                                            |
    |                                                            arguments to this enum variant are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `NaiveDateTime`
help: the type constructed contains `NaiveDateTime` due to the type of the argument passed
   --> src/models/users.rs:241:60
    |
241 |         self.email_verification_sent_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                                            ^^^^^--------------------------^
    |                                                                 |
    |                                                                 this argument influences the type of `Some`
note: tuple variant defined here
   --> /Users/nowfal/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:582:5
    |
582 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

error[E0277]: the trait bound `Vec<u8>: tracing::Value` is not satisfied
  --> src/controllers/auth.rs:70:9
   |
70 |         tracing::info!(pid = user.pid.to_vec(), "user already verified");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `tracing::Value` is not implemented for `Vec<u8>`
   |
   = help: the following other types implement trait `tracing::Value`:
             &'a T
             &'a mut T
             (dyn StdError + 'static)
             (dyn StdError + Send + 'static)
             (dyn StdError + Send + Sync + 'static)
             (dyn StdError + Sync + 'static)
             Arguments<'a>
             Box<T>
           and 34 others
   = note: required for the cast from `&Vec<u8>` to `&dyn tracing::Value`
   = note: this error originates in the macro `$crate::valueset` which comes from the expansion of the macro `tracing::info` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
   --> src/models/users.rs:259:52
    |
259 |         self.reset_sent_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                               ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Vec<u8>`, found `NaiveDateTime`
    |                                               |
    |                                               arguments to this enum variant are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `NaiveDateTime`
help: the type constructed contains `NaiveDateTime` due to the type of the argument passed
   --> src/models/users.rs:259:47
    |
259 |         self.reset_sent_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                               ^^^^^--------------------------^
    |                                                    |
    |                                                    this argument influences the type of `Some`
note: tuple variant defined here
   --> /Users/nowfal/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:582:5
    |
582 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

error[E0308]: mismatched types
   --> src/models/users.rs:274:56
    |
274 |         self.email_verified_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                                   ---- ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Vec<u8>`, found `NaiveDateTime`
    |                                                   |
    |                                                   arguments to this enum variant are incorrect
    |
    = note: expected struct `Vec<u8>`
               found struct `NaiveDateTime`
help: the type constructed contains `NaiveDateTime` due to the type of the argument passed
   --> src/models/users.rs:274:51
    |
274 |         self.email_verified_at = ActiveValue::set(Some(Local::now().naive_local()));
    |                                                   ^^^^^--------------------------^
    |                                                        |
    |                                                        this argument influences the type of `Some`
note: tuple variant defined here
   --> /Users/nowfal/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:582:5
    |
582 |     Some(#[stable(feature = "rust1", since = "1.0.0")] T),
    |     ^^^^

error[E0433]: failed to resolve: use of undeclared type `BlobSize`
 --> src/models/_entities/notes.rs:6:35
  |
6 | #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
  |                                   ^^^^^^^^^^^^^^^^^ use of undeclared type `BlobSize`
  |
  = note: this error originates in the derive macro `DeriveEntityModel` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared type `BlobSize`
 --> src/models/_entities/posts.rs:6:35
  |
6 | #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
  |                                   ^^^^^^^^^^^^^^^^^ use of undeclared type `BlobSize`
  |
  = note: this error originates in the derive macro `DeriveEntityModel` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0433]: failed to resolve: use of undeclared type `BlobSize`
 --> src/models/_entities/users.rs:6:35
  |
6 | #[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
  |                                   ^^^^^^^^^^^^^^^^^ use of undeclared type `BlobSize`
  |
  = note: this error originates in the derive macro `DeriveEntityModel` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
  --> src/models/users.rs:48:41
   |
48 |             this.pid = ActiveValue::Set(Uuid::new_v4());
   |                        ---------------- ^^^^^^^^^^^^^^ expected `Vec<u8>`, found `Uuid`
   |                        |
   |                        arguments to this enum variant are incorrect
   |
   = note: expected struct `Vec<u8>`
              found struct `uuid::Uuid`
help: the type constructed contains `uuid::Uuid` due to the type of the argument passed
  --> src/models/users.rs:48:24
   |
48 |             this.pid = ActiveValue::Set(Uuid::new_v4());
   |                        ^^^^^^^^^^^^^^^^^--------------^
   |                                         |
   |                                         this argument influences the type of `ActiveValue`
note: tuple variant defined here
  --> /Users/nowfal/.cargo/registry/src/index.crates.io-6f17d22bba15001f/sea-orm-1.0.0-rc.7/src/entity/active_model.rs:45:5
   |
45 |     Set(V),
   |     ^^^
help: call `Into::into` on this expression to convert `uuid::Uuid` into `Vec<u8>`
   |
48 |             this.pid = ActiveValue::Set(Uuid::new_v4().into());
   |                                                       +++++++

error[E0599]: `Vec<u8>` doesn't implement `std::fmt::Display`
   --> src/models/users.rs:223:70
    |
223 |         Ok(jwt::JWT::new(secret).generate_token(expiration, self.pid.to_string(), None)?)
    |                                                                      ^^^^^^^^^ `Vec<u8>` cannot be formatted with the default formatter
    |
   ::: /Users/nowfal/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:398:1
    |
398 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    | ------------------------------------------------------------------------------------------------ doesn't satisfy `Vec<u8>: ToString` or `Vec<u8>: std::fmt::Display`
    |
    = note: the following trait bounds were not satisfied:
            `Vec<u8>: std::fmt::Display`
            which is required by `Vec<u8>: ToString`
            `[u8]: std::fmt::Display`
            which is required by `[u8]: ToString`

error[E0599]: `Vec<u8>` doesn't implement `std::fmt::Display`
   --> src/views/auth.rs:18:27
    |
18  |             pid: user.pid.to_string(),
    |                           ^^^^^^^^^ `Vec<u8>` cannot be formatted with the default formatter
    |
   ::: /Users/nowfal/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:398:1
    |
398 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    | ------------------------------------------------------------------------------------------------ doesn't satisfy `Vec<u8>: ToString` or `Vec<u8>: std::fmt::Display`
    |
    = note: the following trait bounds were not satisfied:
            `Vec<u8>: std::fmt::Display`
            which is required by `Vec<u8>: ToString`
            `[u8]: std::fmt::Display`
            which is required by `[u8]: ToString`

error[E0599]: `Vec<u8>` doesn't implement `std::fmt::Display`
   --> src/views/user.rs:16:27
    |
16  |             pid: user.pid.to_string(),
    |                           ^^^^^^^^^ `Vec<u8>` cannot be formatted with the default formatter
    |
   ::: /Users/nowfal/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:398:1
    |
398 | pub struct Vec<T, #[unstable(feature = "allocator_api", issue = "32838")] A: Allocator = Global> {
    | ------------------------------------------------------------------------------------------------ doesn't satisfy `Vec<u8>: ToString` or `Vec<u8>: std::fmt::Display`
    |
    = note: the following trait bounds were not satisfied:
            `Vec<u8>: std::fmt::Display`
            which is required by `Vec<u8>: ToString`
            `[u8]: std::fmt::Display`
            which is required by `[u8]: ToString`

Some errors have detailed explanations: E0277, E0308, E0433, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `myFirstLocoApp` (lib) due to 13 previous errors

Why is it happen? it was working perfectly fine. this error occure suddenly

**Comment by aircjm** [comment]
same problem when i use it

**Comment by kaplanelad** [comment]
Hi
We've made some changes in this area. Could you please test against the `sqlite-seaorm-v1` branch and let us know if it works?

Thanks!

**Comment by nowfalsalahudeen** [comment]
Yeah sure, will test it and let you know

**Comment by kaplanelad** [comment]
@lgfinfo  should fix in version 0.7.0.
