### ISSUE TITLE
increase success factor: sea-orm-cli tweaks

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#686]
* [ ] when generating a new loco app, check for seaorm cli, suggest to install for the user if missing
* [ ] `cargo loco doctor` should check for a compatible seaorm-cli binary (in terms of versions). we should keep a Loco version `<=>` seaorm version compatibility check and fail if seaorm-cli is too old or too new. Keep a "compatible" version and up in loco doctor and update it as needed.

**Comment by farmeroy** [comment]
Hey I'd be up for looking into this. I just started with loco and love the cli experience, i'd love to contribute
