### ISSUE TITLE
In the development mode, an error occurs when starting up. What a bad experience!

### ISSUE THREAD

**Issue by paulzhang5511** [loco-rs/loco#695]
**Description**

In the development mode, an error occurs when starting up. What a bad experience!

![image](https://github.com/user-attachments/assets/5b7c3ec4-aedb-47a0-931f-7614bd201bf7)

**To Reproduce**

Error on startup

**Expected Behavior**

![image](https://github.com/user-attachments/assets/bf3fca68-6057-404a-ab9e-0093a4078ebe)

**Environment:**
Saas app
loco: 0.7.0
os: Windows
npm

**Additional Context**
When invoking the command `cargo loco start`, it can start up normally. Don't run `npm run build` every time.

**Comment by kaplanelad** [comment]
you need to build the clint. 
go to frontend folder and build

**Comment by paulzhang5511** [comment]
This is not very friendly for the first time experience, the operation will report errors

After creating the program, it is necessary to comment out this section of code in order to run it.
![image](https://github.com/user-attachments/assets/5d7549f1-d8fa-486c-8d0f-c3adccf74a24)

**Comment by jondot** [comment]
Thanks for the feedback - @paulzhang5511  maybe when starting up we need to check if the client was built and if not build it for the first time, only in development mode?

**Comment by paulzhang5511** [comment]
In a development environment, it is recommended to comment this configuration so that it does not affect program startup.
![image](https://github.com/user-attachments/assets/f1449844-832e-4644-83fb-bf8334e4d474)

**Comment by lerina** [comment]
My use case does not involve any NPM & Js Frameworks,  so I have to comment out  the static entry in config.development.yaml as a first step. This should be done from the get go, as anybody following the loco guide will be faced with this issue.
Loco should not favors frontend rendering over backend server tera views. 

Until the issue is solved via #694, perhaps the guide should mention commenting out the static frontend bit?

**Comment by jondot** [comment]
@lerina good suggestion. I've made modifications to the configuration + added extensive documentation for each config section + README.

Thanks for finding this @paulzhang5511
