### ISSUE TITLE
Automatically reload code (restart server?)

### ISSUE THREAD

**Issue by szabgab** [loco-rs/loco#70]
If I understand correctly, currently if I make a change to any file I need to stop and start again the demo server to see the effect.
If would be nice if there was a mode that was monitoring all the files (or a subset of the files) and it automatically reloaded the development server.

**Comment by jondot** [comment]
Agreed.
This can be a good first issue, assuming a nice library in Rust can be found that does this easily, or alternatively, some kind of external command line tool (prefer written in Rust) that does it externally (like procman, watchman, etc)

**Comment by kaplanelad** [comment]
@szabgab @jondot 
you can install and work with cargo watch crate: https://crates.io/crates/cargo-watch

**Comment by jondot** [comment]
Looks like this might cut it, closing -- please reopen if needed
