### ISSUE TITLE
Support more SeaOrm datatypes in scaffold

### ISSUE THREAD

**Issue by dev-ardi** [loco-rs/loco#703]
## Feature Request

SeaOrm supports things such as `blob` but `generate scaffold` doesn't support it.

**Describe the solution you'd like**

have `blob` and `blob!` types

**Comment by jondot** [comment]
Thanks!

we'll be happy to accept a PR if you'd like to become a contributor.
it is as easy as adding the types you want here: https://github.com/loco-rs/loco/blob/master/src/gen/mappings.json 

you'll want to also read around in the `gen` module to see how they're used.

if you can't make it, please let me know and we'll add this type quite easily.

**Comment by dev-ardi** [comment]
Currently I'm very busy so I don't think I'll have the time to do it until some time in the future.

**Comment by jondot** [comment]
No worries.
Fixed in master!
