### ISSUE TITLE
Add example for replacing template engine

### ISSUE THREAD

**Issue by DirectorX** [loco-rs/loco#717]
**Description**

Please add an example showing how to replace Terra with something else maybe askama

**Comment by jondot** [comment]
Hi, we have this as an example:
https://github.com/loco-rs/loco/blob/master/examples/demo/src/initializers/hello_view_engine.rs

I believe a full example with askama may be nice, but perhaps outside of the main repo as to not confuse people with too many engines.
Would you like to follow the "hello" example and create such an example repo? We'd be happy to feature it under `loco-rs` or include a link to it in the docs
