### ISSUE TITLE
How can I  implement check function for postgresql in Loco? thank you

### ISSUE THREAD

**Issue by HelloReboot** [loco-rs/loco#718]
CHECK (phone_number IS NOT NULL OR email IS NOT NULL);  
how can i define this in db migration files?

**Comment by trevoranderson** [comment]
This is done by the ORM. Here's an adaptation from one of my tables.

```
  // check() is from sea-query's create.rs
  .check(Expr::col(MyTable::ColumnA).lt(Expr::col(MyTable::ColumnB)))
```

**Comment by HelloReboot** [comment]
thank you so much bro @trevoranderson
