### ISSUE TITLE
Adding a worker to a specific queue

### ISSUE THREAD

**Issue by isaacdonaldson** [loco-rs/loco#721]
**Description**

I couldn't find the relevant information, and while looking into the source code I could not find a way to add options to an `AppWorker`. This seems like it's needed to be able to specify which queue to put a job/worker in?

Looks like there is more than one way to do this: add `sidekiq::WorkerOpts` to `loco::prelude` for use in app, or add `fn opts` to the `AppWorker` trait to allow specifying an `AppWorker` with options. 

My investigation was cursory so the above might not be true. It may also be the fact that specifying the queue is possible, but there are not docs about how to do that even though the ability to supply a custom queue is mentioned.

**Comment by jondot** [comment]
You're correct, I also spotted a fix for this, will push a fix and update here soon, thanks!

**Comment by jondot** [comment]
should be fixed in v0.8.0 (released now)

**Comment by isaacdonaldson** [comment]
Sorry to reopen this @jondot, but this isn't quite what I meant. I ended up fixing it here (https://github.com/loco-rs/loco/pull/759).
