### ISSUE TITLE
Return HTML and in general be able to set content type

### ISSUE THREAD

**Issue by szabgab** [loco-rs/loco#74]
I only found `format::text` and `format::json`. I could not find a built-in way to send HTML pages (with the content type `text/html`. I figured out a way using axum that I included in [this article](https://rust.code-maven.com/getting-started-with-loco), but I guess there is an easier way to do this.

Is there an easier way to send HTML? If not, I'd like to ask for `format::html` or some other way to set the content-type.

**Comment by jondot** [comment]
you are correct, we should offer this, thanks!

**Comment by jondot** [comment]
Implemented
