### ISSUE TITLE
Improve Documentation Site UX

### ISSUE THREAD

**Issue by patrikzudel** [loco-rs/loco#768]
**Description**

I've found Loco just yesterday, today I've noticed that the whole Documentation page has been redone - I am afraid that it is a downgrade in regards to UX. (The design is nice though!)

Due to the scale of the project, users will jump from page to page often. This is exactly where the problem lies, to navigate to a different page in the new docs, you first have to scroll up to the top of the page. This feels unnecessary when working on a 16:9 display as there is quite a bit of whitespace. 

**Suggestion**

When there is sufficient space, the navigation for docs should be on the left or right side. Only the document content should respond to scrolling down so the navigation would always be accessible.

By navigation I mean the Red navigation here - 
![image](https://github.com/user-attachments/assets/9883143d-438c-4076-87da-8ee731aaacbb)

**Comment by ammoti** [comment]
Hi,
First of all I want to congratulate all loco.rs team for the new UI. 
I did not want to open new issue for this, in dark mode blog articles commands not display very well, I hope you will fix it next update.
<img width="1728" alt="Screenshot 2024-09-20 at 05 30 48" src="https://github.com/user-attachments/assets/8ed9ab98-1147-4287-a772-268969a491b1">
