### ISSUE TITLE
Typo `Loca` in the docs under `Models -> Seeding`

### ISSUE THREAD

**Issue by tobsz** [loco-rs/loco#776]
**Description**

The second paragraph of the subsection "Seeding“ of the [Models documentation](https://loco.rs/docs/the-app/models/) starts with `Loca` instead of `Loco`.

**Screenshot**

![Screenshot_20240921-221806.png](https://github.com/user-attachments/assets/c06150dc-8039-43a6-9151-e1f0c64c0caa)

**Comment by jondot** [comment]
Thanks, fixed!
