### ISSUE TITLE
RFC: the road to "Active Job" - a queue/worker abstraction layer

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#779]
Hi all,

**This is a "request for comments" issue. Please feel free to add comments, pointers, ideas under this thread.**

I'd like to use this issue to define a goal:

> Create an abstraction layer for concrete queue implementations for background jobs to provide cheaper, easier, or "reuse existing infra" alternatives to Redis.

Although current solution based on sidekiq-rs is **fantastic** and really, everyone should have *some kind of* access to a Redis instance, there is *some value* in abstracting over this infrastructure.

We'd like to create a provider-based implementation for this area, just like our Storage and Cache subsystems. Prior work in Rails is ActiveJob, which manifested AMQP based workers (which I was the author of), and other kinds of queue providers.

People may want to use solutions other than Redis *primarily* because they already "have something" running in their organization. Then, other people may have different security, or other operational requirements which require a different system to plug jobs into.

-------------

Leading options:

* Mainly deal with building a trait-providers sub system, then have Redis as the primary concrete provider. Async and Foreground remain "exception to the rule" and bypass the provider system, as it is today.
* The `Processor` can be a tough point to abstract. Either way, each provider must implement a processor.

Notes:

* The main alternative to Redis should be **Postgres**. Selecting this provider should create a "one in a box" system where you only need a server and postgres to build apps. This can be implemented with postgres push or polling a table.
* Secondly, Sqlite (which can be done with the same postgres implementation, jobs table, etc) - will create a "no dependencies" single binary deployment for every app. This can be implemented with polling a table.
* The rest of providers: SQS, AMQP, etc. should come as first-come first-serve.

**Comment by isaacdonaldson** [comment]
I really like the idea of supporting more job queue implementations, namely the Postgres backed one (SQLite as well). I think that the [Oban](https://github.com/oban-bg/oban) Elixir job queue is a good one to reference. I don't have much experience with SQS or others so I can't speak to those.

**Comment by schungx** [comment]
Yes, already Redis is awsome, somethings we don't need that much power.  We just need to schedule a few non-timing-critical tasks, and want to have things "Just Work."

**Comment by jondot** [comment]
#797 now implements this RFC.

It's been quite challenging to implement polymorphism at the worker level since both the worker and the args are polymorphic and Rust has the 'trait as object' limitations (traits cannot be with generics), and so I've resorted to *enum* as a way to implement the "provider" pattern.

This means that every additional provider will hit the main `enum` match clauses.
Currently Redis via existing `sidekiq` is supported, with modified and better abstration, and a from-scratch postgres based queue (using sqlx).

**Comment by isaacdonaldson** [comment]
@jondot - If we support SQLite as a backend for the database, we should also support it as a backend for the new job system. I don't think SQLite has `UPDATE SKIP LOCKED`, but I believe it only supports one reader at a time so that might not be needed?

**Comment by jondot** [comment]
Yes this logic makes sense. And you’re correct SQLite has a different mechanism (but really close in terms of query)
Only reason I did I not do it is thinking SQLite is not naturally central or supports distributed jobs so what would be the point. 
but I can check and see if I can go for it in the sake of feature parity as you mention.

**Comment by isaacdonaldson** [comment]
I think it would be a nice support feature to allow those who want to run a bundled app on a single server, given Rust's runtime characteristics it would be nice to support that.

Another nice to have in a job queue system is the ability to schedule jobs for a future time. I had a PR open in the last job system to do that and don't mind implementing that again 😄

**Comment by jondot** [comment]
It should be super easy with all the new infra
I’m finishing up some API design and will ping you

**Comment by georgeboot** [comment]
Main reason for us not to want queues in redis, is that we generally run redis in-memory only (primary for cache) which means that when it reboots etc, the current queue will get lost.

It would also be amazing if the queue drivers all support the concept of chaining ("run job y after this job completes") and batch chaining (enqueue 10 jobs and once all of them have been processed, run job y).

**Comment by jondot** [comment]
0.10.0 now released with the new workers subsystem. 
we would happily accepts improvements to the new pg worker and an addition of an sqlite queue provider.
