### ISSUE TITLE
When using react, run `npm/yarn/pnpm build` while building the app

### ISSUE THREAD

**Issue by assapir** [loco-rs/loco#786]
**Description**

If one tries to start their app which bundled with react frontend without building it first, they will an error stating `Error: Message("one of the static path are not found, Folder `frontend/dist` fallback: `frontend/dist/index.html`")`

**To Reproduce**

Create a SaaS app with React frontend. run `cargo loco run`

**Expected Behavior**

Suggest to have a `build.rs` that will run the build for the fronted. Even better will be that if it's in dev mode, it will start the react app in dev mode

**Comment by van-sprundel** [comment]
A `build.rs` would also run if we were to call something like `cargo loco help`. It seems like this would be a good feature for the cli though. `cargo loco start` would build the frontend before serving

**Comment by Sillyvan** [comment]
I do like the idea of a dev mode that can run multiple processes in the background. like a frontend dev server, tailwind cli --watch, etc

**Comment by jondot** [comment]
After some thoughts, we're going to handle this for now in more specific instruction post-generating the app.
We will don't know if it is correct to take ownership of the asset build pipeline since we allow anyone to plug any pipeline they want.
