### ISSUE TITLE
Support refresh tokens for creating an idToken (JWT)

### ISSUE THREAD

**Issue by assapir** [loco-rs/loco#787]
**Description**

If I understand the code correctly, currently there is no way to create a JWT token without logging in, and by default, it expires in  7 days. This is a security risk for me - if someone stole my JWT token, they can use it in the next 7 days until it expires. It also means that the user will need to re-login every 7 days.

**To Reproduce**

Create an app /shrug

**Expected Behavior**

I suggest creating a complementary mechanism for authentication. In this mechanism, one can use a refresh token to create an IdToken (what currently is used for authentication).
This is how it works:
Upon login, the response isn't for JWT only (which is the `IdToken`) but also includes a `RefreshToken`, which might be anything, preferably long and unguessable. 
This refresh token can be used to create an IdToken which is valid for only one hour - which means if an attacker puts their hands on it they will be able to do bad things only for an hour. The refresh token itself has a longer lifetime - let's say a year - and can be stored on a cookie, for example. to generate the JWT from the frontend whenever needed.
The refresh token should be stored in a way where it's easy to revoke it - let's say on a Redis instance - and if an attacker has their hand on it, the only thing the user needs to do is call `revoke all` API that will delete all their refresh tokens from the instance, so now to create a new one they will need to log in again, to create a new refresh token.

To conclude:
1. The user login -> response has a `refresh token` and the refresh token is saved on the server side.
2. The user/frontend saves this token (e.g. in a cookie) and calls an endpoint like `/refresh` to create a short-living JWT.
3. The user uses this JWT (AKA IdToken) to do operations on the server side.
4. In case of JWT stolen - no problem - it's only valid for an hour, and can't be used to create a refresh token.
5. In case of refresh token is stolen - there is a way to invalidate (using the JWT) all the current user refresh tokens
6. User login - they now have a new refresh token, all good.

**Comment by kaplanelad** [comment]
@assapir we are accepting PR :)

**Comment by assapir** [comment]
I would need some pairing on that, and some thoughts on design - should we (re)introduce redis? Should we store the refresh tokens on the db?

**Comment by trevoranderson** [comment]
> It also means that the user will need to re-login every 7 days
This isn't necessarily the case. The user's token expires in 7 days by default (configurable), but you can serve the user a refreshed token in response to requests to reset the clock. Thus the login only has to happen if inactive for the entire duration. Here's a snippet for creating a new token based on the old one with the user's id.

```
jwt::JWT::new(&jwt.secret)
                .generate_token(&jwt.expiration, pid, None)
```

>  if someone stole my JWT token, they can use it in the next 7 days until it expires
By default, yes, but you can manually expire them by having a deny list of tokens that you do not want to allow to be used and store that in the DB or cache. Would want to do a token validation middle-ware step so this verification happens automatically.
