### ISSUE TITLE
Corrections in The Loco Guide Page

### ISSUE THREAD

**Issue by ImplFerris** [loco-rs/loco#789]
**Description**

There are few small issues in the The Loco Guide Page (in the loco.rs site). 

1. The tour link is broken and displays page not found
2. The note says "Nevertheless, the routes: /_health and /_ping are exceptions, they stay at the root.". However, this is not true for REST API. You can reach it via "http://localhost:5150/api/_ping" only

**To Reproduce**
❯ loco new
✔ ❯ App name? · myapp
✔ ❯ What would you like to build? · Rest API (with DB and user auth)
✔ ❯ Select a DB Provider · Sqlite
✔ ❯ Select your background worker type · Async (in-process tokyo async tasks)

**Expected Behavior**

1. update the document in the website regarding the URL
2. Fix the broken the tour link

**Environment:**

**Additional Context**

I have attached the screenshots for reference

![broken-link](https://github.com/user-attachments/assets/8baab995-c365-47ea-b23e-5b834742a2e1)
![notes](https://github.com/user-attachments/assets/4143a36c-e2e4-4ea0-a7f4-b3083b6c2bf8)
![curl](https://github.com/user-attachments/assets/36245ee1-b488-44a3-972c-3f98c523b2d6)

**Comment by PedroTurik** [comment]
What would be the correct solution for the second problem? Change the docs, or change where the healthcheck routes go?

**Comment by daflyinbed** [comment]
https://loco.rs/docs/processing/scheduler/
![IMG_20241002_105132.jpg](https://github.com/user-attachments/assets/7eb02e24-cacf-49c0-8781-44294c15827d)

this link is broken too.

**Comment by ImplFerris** [comment]
> What would be the correct solution for the second problem? Change the docs, or change where the healthcheck routes go?

i would suggest to just update the docs. because the url path makes sense for api
