### ISSUE TITLE
Shocking lack of references to Ozzy Osbourne in source code

### ISSUE THREAD

**Issue by rbalicki2** [loco-rs/loco#790]
**Description**

* There are no references to Ozzy Osbourne in the source code, despite the logo (etc) being a "crazy train". This is a tremendous missed opportunity to make inroads into the crucial hair-metal-loving Rust users demographic.

**To Reproduce**

Cmd+f + o + z + z + y + enter

**Expected Behavior**

* 100+ matches

**Environment:**

GoboLinux 017

**Additional Context**

Keep up the great work!

**Comment by jondot** [comment]
You are correct!
This is a missed opportunity. I will have to settle the historical conflict between Randy Rhodes and Eddie Van Halen (which we do reference) but once that is done we’ll see where to include Crazy Train!

**Comment by jondot** [comment]
Achievement unlocked, see #791 
Thanks!

**Comment by rbalicki2** [comment]
Wow, record time! 💯💯
