### ISSUE TITLE
error when use mysql database.

### ISSUE THREAD

**Issue by longjin1991** [loco-rs/loco#794]
**Description**

I use mysql with loco, 
when run:
cargo loco generate scaffold post title:string content:text --api.
add run:
cargo loco db migrate
it error:
  --> src\controllers\auth.rs:70:39
    |
70  |         tracing::info!(pid = user.pid.to_string(), "user already verified");
    |                                       ^^^^^^^^^ `Vec<u8>` cannot be formatted with the default formatter
 src\models\users.rs:48:41
   |
48 |             this.pid = ActiveValue::Set(Uuid::new_v4());
   |                        ---------------- ^^^^^^^^^^^^^^ expected `Vec<u8>`, found `Uuid`
   |                        |
   |                        arguments to this enum variant are incorrect
please fix it
![Screenshot 2024-10-01 203927](https://github.com/user-attachments/assets/6d1483ff-1abe-4268-85e0-a95830cc02ed)

**Comment by kaplanelad** [comment]
@lolongjin1991 which seaorm-cli are you using? 
if lower then 1.x.x can you try to install the latest?

**Comment by longjin1991** [comment]
> @lolongjin1991 which seaorm-cli are you using? if lower then 1.x.x can you try to install the latest?

i use loco anh seaorm latest:
loco-cli 0.2.9
sea-orm-cli 1.0.1
please suport mysql or mariadb database.

**Comment by kaplanelad** [comment]
If you'd like to contribute, we welcome pull requests!
