### ISSUE TITLE
"The Loco Guide" dose not work

### ISSUE THREAD

**Issue by Chris1717** [loco-rs/loco#801]
I'm new to loco and wanted to do the tour.

I installed the CLIs
```
cargo install loco-cli
cargo install sea-orm-cli
```

Started the project setup

```
christian@MBP14vohristian rust % loco new
✔ ❯ App name? · myapp
✔ ❯ What would you like to build? · SaaS app (with DB and user auth)
✔ ❯ Select a DB Provider · Sqlite
✔ ❯ Select your background worker type · Async (in-process tokyo async tasks)
✔ ❯ Select an asset serving configuration · Client (configures assets for frontend serving)

🚂 Loco app generated successfully in:
/Users/christian/Developer/rust/myapp

- assets: You've selected `clientside` for your asset serving configuration (remember to build your frontend in `frontend/`)
```
Changed into the "myapp" directory, and started the server:

`cargo loco start
`
Complies fine, but

```
2024-10-06T07:40:22.221004Z  INFO app: loco_rs::controller::app_routes: [Middleware] +log trace id environment=development
Error: Message("one of the static path are not found, Folder `frontend/dist` fallback: `frontend/dist/index.html`")
```

Loco does not start.

I would appreciate help.

**Comment by lerina** [comment]
did you build your front end?
If you don't have a frontend (vue, react , ...) then you probably want to use 
tera serverside

**Comment by Chris1717** [comment]
The guide does not ask to built a front end.
Do I get something wrong?

**Comment by vitoraguila** [comment]
Yeah, also running in the same issue

**Comment by ryane** [comment]
Yeah, building the frontend (following the instructions in the generated frontend/README.md) gets past the issue. Since the guide suggests that you should choose frontend serving, it should probably include (or at least link to) the instructions on building the frontend.

**Comment by lerina** [comment]
The cli actually reminds you to do so:

- assets: You've selected `clientside` for your asset serving configuration (remember to build your frontend in `frontend/`)

**Comment by chainyo** [comment]
The next command asks you to choose `--api`, `--htmx` or `--html` this could be updated too.

**Comment by yonas** [comment]
Also, the API URL is now `http://localhost:5150/**api**/posts` not `http://localhost:5150/posts`

**Comment by jondot** [comment]
closing since @isaacdonaldson have addressed it, thanks! 👍
