### ISSUE TITLE
more complex references?

### ISSUE THREAD

**Issue by drdozer** [loco-rs/loco#814]
## I can't see how to add a reference that is named

The generate scaffold command seems to support things of the form <type>:reference and <type>:references for letting the type being generated to link to <type>.

In my use-case, I am writing a choose your own adventure style document. So each story_page has a title and some text. Then, each story_page needs to have zero or more links to other pages, each link with a brief description. This is a classic join table, I think, but the relation would look something like:

```
link_from : story_page.id
link_to: story_page.id
```

where this is a many-to-many, but on the story_page view, we want to see all the outbound links, and possibly all inbound links as well for debug during editing.

I can't see how to generate a scaffold for this kind of relationship though. I can do story_page:references which would be fine for one of these two links, but then what do I do for the other one? And how do I name the links by role?

I have probably missed something obvious in the documentation, but I can't find it :/

**Comment by jondot** [comment]
For simple 1:M relationship, scaffold would work with not much effort. Did you look at https://loco.rs/docs/the-app/models/#relationships and the `--link` flag?

**Comment by drdozer** [comment]
> For simple 1:M relationship, scaffold would work with not much effort. Did you look at https://loco.rs/docs/the-app/models/#relationships and the `--link` flag?

I could see how to use that to join a table to itself. I need the choices table to be a many- many from story pages to story pages. From where you make a choice to where that choice takes you.
