### ISSUE TITLE
loco-cli should auto-install sea-orm-cli if missing

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#82]
Probably wise to also ask before installing it, and explain why it is needed.

**Comment by AbhilashGade** [comment]
Can I pick this issue?

**Comment by kaplanelad** [comment]
@jondot maybe we can fix the seaorm cli crate and make the generator entry to use via the crate instead of the cli installation?

what do you think?

**Comment by kaplanelad** [comment]
The problem is that the sea-orm is needed only on specific templates (saas).
We could do something smarter and check in the lib that:
Check if the user uses the DB feature and the migration commands in the configuration are enabled (migration, truncate, reset..) and then check if seaorm-cli is installed. and if not, stop the service and prompt a pretty message.

What do you think?

**Comment by jondot** [comment]
yes sounds good!

**Comment by kaplanelad** [comment]
@AbhilashGade you can feel free and take it. 
you can implement it in the lib instead of the CLI. 
see that the validation should be only when `with-db` feature is enable

**Comment by kaplanelad** [comment]
> @kaplanelad yeah on it

just make sure that you not installing automatically sea-orm. i think it is better to return an pretty error with explanation

**Comment by AbhilashGade** [comment]
Okay how do I test this

**Comment by kaplanelad** [comment]
@AbhilashGade you can use (check_seaorm_cli)[https://github.com/loco-rs/loco/blob/master/src/doctor.rs#L132] which doing the checks that you needs

**Comment by AbhilashGade** [comment]
So do I do something like this 

`fn check_sea_orm() {
    println!(" SeaORM is not installed. SeaORM is a powerful ORM for Rust that provides convenient database abstractions. It is required for this feature. Would you like to install it? (y/n)");

    let mut input = String::new();
    std::io::stdin().read_line(&mut input).unwrap();
    let input = input.trim().to_lowercase();

    if input == "y" || input == "yes" {
        println!("Installing SeaORM... ");
        std::process::Command::new("cargo")
            .arg("install")
            .arg("sea-orm")
            .output()
            .expect("Failed to install SeaORM");
    } else {
        println!("SeaORM is required for this feature. Please install it to continue.");
    }
}
`

**Comment by kaplanelad** [comment]
> > @kaplanelad yeah on it
> 
> just make sure that you not installing automatically sea-orm. i think it is better to return an pretty error with explanation

Did you see my previous message? I believe there's no need to install the sea-orm-cli. Handling the installation process might be unnecessary and open to potential problems. 
Prompting the user with the necessary details should suffice. 

You can take a look at this PR: #212. if you think we can to it better or prettier you are more then welcome to advise
