### ISSUE TITLE
Clean Starter

### ISSUE THREAD

**Issue by tdaron** [loco-rs/loco#820]
## Feature Request

**Describe the solution you'd like**

Hi ! Would it be possible to have some kind of a "Clean" starter, which would be like the SaaS one, but without any pre-made model-controller and views (user, notes) nor frontend?  

**Describe alternatives you've considered**

Make a SaaS project and spend time to clean the whole thing up :)

**Comment by jondot** [comment]
yes, that makes sense! we'll do it.

**Comment by Sillyvan** [comment]
Honestly maybe the starters just need some cleanup & more options.

If you create the Saas one "asset serving from the server" you still get a frontend folder with react inside.
Same for the exmaples folder

**Comment by jondot** [comment]
handled as part of #846
