### ISSUE TITLE
Add Spanish README.MD

### ISSUE THREAD

**Issue by lautarolopez4** [loco-rs/loco#821]
**Is your feature request related to a problem? Please describe.**

It would be useful for Spanish-speaking users to have access to the project documentation in their native language. Currently, the README is only available in English, which may create a barrier for those who are not fluent, limiting their ability to contribute or use the project effectively.

**Describe the solution you'd like**

I propose adding a Spanish version of the README file. This would allow Spanish-speaking users to easily access all relevant information about the project, including features, installation instructions, and usage guidelines, fostering greater inclusivity and engagement.

**Comment by kaplanelad** [comment]
Hi @username,

We'd be happy to accept a pull request for this. If you're interested, feel free to contribute by translating the README into Spanish, and we’ll review it once submitted.
