### ISSUE TITLE
Custom Banner

### ISSUE THREAD

**Issue by leaderit** [loco-rs/loco#827]
It would be good to have an option for custom banner on start.
Extended information, diagnostics etc.

## The patch for the Feature is

[loco-rs+0.9.0.patch](https://github.com/user-attachments/files/17349376/loco-rs%2B0.9.0.patch)

WBRs,
Valerii

**Comment by kaplanelad** [comment]
Hi! Thank you for the suggestion. 
To better understand your request, could you please provide an example of the custom banner output you're expecting? It would also be helpful to know:

- What specific fields or information would you like to include in the banner?
- Where you'd like each of those fields to be displayed.

This will help us better tailor the feature to your needs. Thanks!

**Comment by kaplanelad** [comment]
adding `--no-banner` flag
