### ISSUE TITLE
first run 'cargo loco start' failed

### ISSUE THREAD

**Issue by greysoftcrazy** [loco-rs/loco#85]
**Description**

/error[E0432]: unresolved import `loco_rs::hash`
 --> src/models/users.rs:3:11
  |
3 |     auth, hash,
  |           ^^^^ no `hash` in the root
  |
  = help: consider importing one of these items instead:
          std::hash
          core::hash

and mode errors

**To Reproduce**

cargo loco start

**Comment by kaplanelad** [comment]
Thanks @greysoftcrazy for the update. 
The earlier released version encountered compatibility issues with the `loco-rs` crate. I've just published `loco-rs` version 0.1.4. Feel free to delete the cargo.lock file and run the process again;  or run `loco new` for creating new template.
it should now fetch the 0.1.4 version, resolving the compatibility concerns.

Additionally, I've opened issue #86 to prevent such situations in the future.

thanks.

Keeping this issue open in case there is still problem in your side
