### ISSUE TITLE
cargo loco generate controller guide -k api

### ISSUE THREAD

**Issue by nagashi** [loco-rs/loco#859]
**Description**

Per doc, https://loco.rs/docs/getting-started/guide/ , running the following code: 
`cargo loco generate controller guide -k api` 
should generate the controller body seen below:
```rust
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;

pub async fn echo(req_body: String) -> String {
    req_body
}

pub async fn hello(State(_ctx): State<AppContext>) -> Result<Response> {
    // do something with context (database, etc)
    format::text("hello")
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("guide")
        .add("/", get(hello))
        .add("/echo", post(echo))
}
```

'What was generated by the loco_cli in guide.rs is the following code:
```rust
   #![allow(clippy::missing_errors_doc)]
   #![allow(clippy::unnecessary_struct_initialization)]
   #![allow(clippy::unused_async)]
   use loco_rs::prelude::*;
   use axum::debug_handler;
  
   #[debug_handler]
   pub async fn index(State(_ctx): State<AppContext>) -> Result<Response> {
       format::empty()
   }
  
   pub fn routes() -> Routes {
       Routes::new()
           .prefix("guides/")
           .add("/", get(index))
   }
```

**To Reproduce**

I ran the command `rust cargo loco generate controller guide -k api` in the myapp directory.

Below are the entries in Cargo.toml:
```rust
[workspace]

[package]
name = "myapp"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "myapp-cli"

[dependencies]

loco-rs = { version = "0.10.1" }
migration = { path = "migration" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.33.0", default-features = false }
async-trait = "0.1.74"
tracing = "0.1.40"
chrono = "0.4"
validator = { version = "0.18" }
sea-orm = { version = "1.0.0", features = [
  "sqlx-sqlite",
  "sqlx-postgres",
  "runtime-tokio-rustls",
  "macros",
] }

axum = "0.7.5"
include_dir = "0.7"
uuid = { version = "1.6.0", features = ["v4"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
fluent-templates = { version = "0.8.0", features = ["tera"] }
unic-langid = "0.9.4"

[[bin]]
name = "myapp-cli"
path = "src/bin/main.rs"
required-features = []

[[bin]]
name = "tool"
path = "src/bin/tool.rs"
required-features = []

[dev-dependencies]
serial_test = "3.1.1"
rstest = "0.21.0"
loco-rs = { version = "0.10.1", features = ["testing"] }
insta = { version = "1.34.0", features = ["redactions", "yaml", "filters"] }
```

**Expected Behavior**

Within my src/controllers/guide.rs file, I expected to see the following:
```rust
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;

pub async fn echo(req_body: String) -> String {
    req_body
}

pub async fn hello(State(_ctx): State<AppContext>) -> Result<Response> {
    // do something with context (database, etc)
    format::text("hello")
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("guide")
        .add("/", get(hello))
        .add("/echo", post(echo))
}
```

**Environment:**

My OS is a Mac, which is up to date. Rust version is 1.81.0 (not nightly)

**Additional Context**

In order for me to proceed past this issue, I had to copy the expected output from the doc to my guide.rs.

**Comment by isaacdonaldson** [comment]
It's a little hard to see what is going on because the code you posted is not formatted, do you mind formatting it so it is more readable?

It's also not clear what the problem is that you are facing. Is the issue that the docs do not generate the same code as the CLI tool? Is that causing any compilation issues, or are you just noting that to make us aware? A little more clarification is needed.

**Comment by nagashi** [comment]
Sorry it took so long to reply.  The docs do not generate the same code as the CLI tool.  After running the command
`cargo loco generate controller guide -k api`, I expected to see the following in the guide.rs file:

#![allow(clippy::unused_async)]
use loco_rs::prelude::*;

pub async fn echo(req_body: String) -> String {
req_body
}

pub async fn hello(State(_ctx): State) -> Result {
// do something with context (database, etc)
format::text("hello")
}

pub fn routes() -> Routes {
Routes::new()
.prefix("guide")
.add("/", get(hello))
.add("/echo", post(echo))
}

*** What I actually had in my generated file is as follows:

#![allow(clippy::missing_errors_doc)]
#![allow(clippy::unnecessary_struct_initialization)]
#![allow(clippy::unused_async)]
use loco_rs::prelude::*;
use axum::debug_handler;

#[debug_handler]
pub async fn index(State(_ctx): State<AppContext>) -> Result<Response> {
    format::empty()
}

pub fn routes() -> Routes {
    Routes::new()
        .prefix("guides/")
        .add("/", get(index))
}

** I hope this clears up what I was attempting to address earlier.  Let me know if you have any questions/concerns and thanks for looking into this.

**Comment by nagashi** [comment]
> because

I totally agree with your assessment that the way I previously had the issue displayed caused it to be difficult to read thus understand.  It has been corrected.  I hope this was the proper way to reply to you as I'm still getting use to this.
