### ISSUE TITLE
Cast playlist on youtube is sorted incorrectly

### ISSUE THREAD

**Issue by joshka** [loco-rs/loco#867]
**Description**

I loaded up the youtube cast playlist and expected to be able to watch them in order to get a feel for the progression of loco and noticed that the list starts at 7. This means watching them in order is a manual task rather than letting the playlist play

<img width="393" alt="image" src="https://github.com/user-attachments/assets/27822dcb-b042-425b-8fff-61e35a33aaad">

**Comment by jondot** [comment]
Thanks! I've now sorted it in the way you've recommended 👍
