### ISSUE TITLE
Adding clear instructions on how to update a loco app

### ISSUE THREAD

**Issue by darricheng** [loco-rs/loco#868]
**Description**

I saw the recent release of loco v0.11, and was wondering what does it mean to update my loco app from 0.10 to 0.11. For example, what are the steps that I should take as a user of loco to update my app? Is it just a matter of updating the loco cli? Or are there other steps that I have to take as well?

**Additional Context**

I just started my first loco app, and have been trying to explore around because I wish to build actual applications with loco. As a new user, when I saw the new update, I'm at a loss for what to do though. At the moment, I have nothing developed yet, so I can easily start from scratch again, but I can imagine for someone deeper into development such information could be useful, especially if there are breaking changes across versions too.

**Comment by jondot** [comment]
Hi,
Thanks - I agree. There needs to be some instruction regarding the CLI.
Usually it just requires updating the version, and following the CHANGELOG to see if there's any code migration:
https://github.com/loco-rs/loco/blob/master/CHANGELOG.md#v0110
