### ISSUE TITLE
Create schedual ci

### ISSUE THREAD

**Issue by kaplanelad** [loco-rs/loco#87]
We need to establish a scheduled CI task that performs the following:

1. Executes loco new to generate a new loco app.
2. Builds the app and verifies the generator sites are functioning correctly.

Implementing this CI task will enable us to identify and address potential errors proactively, preventing any impact on our users. Refer to the example issue #85 for more details.

**Comment by kaplanelad** [comment]
hey @arferreira 
this issues are already done. 
you can choose another issue and I'll love to help you

**Comment by arferreira** [comment]
Hey @kaplanelad I was just looking to contribute with something, I was using my own framework in my current projects. 
I liked loco's spectrum.
Just let me know if I can contribute with this.

**Comment by kaplanelad** [comment]
Your contributions to our project are greatly appreciated! Feel free to choose an issue that interests you, and we can discuss the details there.
