### ISSUE TITLE
Consider squash merging

### ISSUE THREAD

**Issue by joshka** [loco-rs/loco#873]
**Description**

The git history of this repo is pretty difficult to follow, which may bite you in the long term. Consider using github's squash merge to avoid this. I used to personally hate the squash merge, but having worked on a library with 10k stars and 3M+ downloads, I've very much come around to it as fairly reasonable (or perhaps the least unreasonable option).

<img width="1390" alt="image" src="https://github.com/user-attachments/assets/90417a5a-2ec6-4d07-abb3-1d8a4641707c">

**Comment by yorigcs** [comment]
I also recommend this way.
Squash commit all PR
cp pr that will be put in some release and merge commit the release in master.

**Comment by jondot** [comment]
Definitely!
Thanks for the feedback, we'll start implementing this workflow right away ❤️
