### ISSUE TITLE
Adding a new migration when there is only one present results in broken code

### ISSUE THREAD

**Issue by darricheng** [loco-rs/loco#879]
**Description**

When there is only one migration in the `/migration/src/lib.rs` file, adding a new migration via CLI results in broken code.

Before:

```rust
#![allow(elided_lifetimes_in_paths)]
#![allow(clippy::wildcard_imports)]
pub use sea_orm_migration::prelude::*;

mod m20220101_000001_users;

pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
        vec![Box::new(m20220101_000001_users::Migration)]
    }
}
```

After:

```rust
#![allow(elided_lifetimes_in_paths)]
#![allow(clippy::wildcard_imports)]
pub use sea_orm_migration::prelude::*;

mod m20220101_000001_users;

mod m20241020_051916_tests;
pub struct Migrator;

#[async_trait::async_trait]
impl MigratorTrait for Migrator {
    fn migrations() -> Vec<Box<dyn MigrationTrait>> {
            Box::new(m20241020_051916_tests::Migration),
        vec![Box::new(m20220101_000001_users::Migration)]
    }
}
```

**To Reproduce**

1. Remove all but one migration in the `/migration/src/lib.rs` file as shown above.
2. Run a command that generates a migration, e.g.`cargo loco generate model test name:string`

**Expected Behavior**

The new migration should be added into the `vec![]` macro correctly.

**Misc**

I'm willing to contribute a fix, though I'll need some guidance to find the source of the issue because I'm still unfamiliar with the codebase.

**Comment by jondot** [comment]
Thanks! looks like something we should fix.
I'm wondering how did you get a single migration? (most of the starters have multiple)

**Comment by jondot** [comment]
Look here: https://github.com/loco-rs/loco/commit/26f0069bbbc25bce209d6298e6d62be93d2ec36a
This should give you a sense for how to fix generator related issues in the future :)
Thanks for catching this!

**Comment by darricheng** [comment]
I was following the file changes in #846 on what files and code to edit, so that I could remove the notes model and related code from the saas starter.
