### ISSUE TITLE
Adding CORS support from configuration

### ISSUE THREAD

**Issue by brahimABD98** [loco-rs/loco#89]
first of all great project really great, am currently it as a rest API and I am consuming the controllers endpoint and I had to setup CORS , so my question is there a plan to add support for  API endpoints

**Comment by kaplanelad** [comment]
het @brahimABD98,
yes sure,  we will implement it soon.

**Comment by kaplanelad** [comment]
Some context on this issue, 
we should add a cors middleware to the list of middleware that we have today.
steps:

1.  enable `cors` feature in tower_http lib (that we are already using)
2. Add the new middleware into the [config](https://github.com/loco-rs/loco/blob/master/examples/demo/config/development.yaml#L22). don't forget to add it to all environments and also to the starters
3. If the cors middleware is enabled, we should add the layer [here](https://github.com/loco-rs/loco/blob/master/src/controller/app_routes.rs#L181).

Notes, 
make sure that we can configure the cors option such as `allow origin`/`allow methods ` and more.

**Comment by brahimABD98** [comment]
@kaplanelad for developement it should be straight forward to add cors middleware  permissible or very_permissible are both  viable config provided by tower_http but how about production ?

**Comment by brahimABD98** [comment]
@kaplanelad oh am asking in I want to make a pull request to add support for cors how should I handle  production

**Comment by kaplanelad** [comment]
@brahimABD98 sorry, I'm not sure I understand what you mean by handling in production.
can you elaborate?

**Comment by brahimABD98** [comment]
@kaplanelad how should the user provide their own  cors config :
from the yml file or  by passing  their cors config to the middleware

**Comment by kaplanelad** [comment]
I think something like that is in the config.rs, which converts out *.yaml config to a Config.
```rust

#[derive(Debug, Clone, Deserialize, Serialize)]
pub struct Middlewares {
    ...
    pub cors: Option<CorsMiddleware>,
}


pub struct CorsMiddleware {
    pub enable: bool,
    pub allow_methods: Option<vec![...]>,
    pub allow_methods: Option<vec![...]>,
    pub allow_origin: Option<vec![...]>,
}
```


@jondot what do you think?

**Comment by jondot** [comment]
Looks good, note you have `allow_methods` twice
But all in all, we can take example from 2 worlds: node, and rails:

https://github.com/cyu/rack-cors:

```ruby
use Rack::Cors do
  allow do
    origins 'localhost:3000', '127.0.0.1:3000',
            /\Ahttp:\/\/192\.168\.0\.\d{1,3}(:\d+)?\z/
            # regular expressions can be used here

    resource '/file/list_all/', :headers => 'x-domain-token'
    resource '/file/at/*',
        methods: [:get, :post, :delete, :put, :patch, :options, :head],
        headers: 'x-domain-token',
        expose: ['Some-Custom-Response-Header'],
        max_age: 600
        # headers to expose
  end

  allow do
    origins '*'
    resource '/public/*', headers: :any, methods: :get

    # Only allow a request for a specific host
    resource '/api/v1/*',
        headers: :any,
        methods: :get,
        if: proc { |env| env['HTTP_HOST'] == 'api.example.com' }
  end
end
```

https://www.npmjs.com/package/cors#configuring-cors - which combines configuration and logic that a user specifies

----
Finally, I would look at this: https://docs.rs/axum/latest/axum/middleware/index.html and think about turning the "builder" style configuration, into a "struct style" configuration -- which we can load from YAML.

**Comment by kaplanelad** [comment]
@brahimABD98 we have added cros middleware functionality into Loco's. You can look forward to using it in the upcoming version! 🚀
