### ISSUE TITLE
Channels aren't working anymore with socket.io-client

### ISSUE THREAD

**Issue by chainyo** [loco-rs/loco#892]
**Description**

The `channels` feature is not working with the most recent __loco-rs__ `v0.10.1` version and __socketioxide__ `v0.14.0` as presented in the [documentation](https://loco.rs/docs/extras/channels/) and/or in the [chat-rooms](https://github.com/loco-rs/chat-rooms) example.

**To Reproduce**

I git cloned the chat-rooms example repository and updated the both dependencies to reproduce the recent setup by updating the dependencies:

```bash
git clone https://github.com/loco-rs/chat-rooms.git
cd chat-rooms
```

* Update the cargo.toml file

```toml
loco-rs = { version = "0.10.1", default-features = false, features = [
  "cli",
  "channels",
] }
...
tokio = { version = "1.33.0", features = ["rt-multi-thread"]}
```

* Update the `src/app.rs` file:

```rs
use async_trait::async_trait;
use loco_rs::{
    app::{AppContext, Hooks},
    bgworker::Queue,
    boot::{create_app, BootResult, StartMode},
    controller::{channels::AppChannels, AppRoutes},
    environment::Environment,
    task::Tasks,
    Result,
};

use crate::channels;

pub struct App;
#[async_trait]
impl Hooks for App {
    fn app_name() -> &'static str {
        env!("CARGO_CRATE_NAME")
    }

    fn app_version() -> String {
        format!(
            "{} ({})",
            env!("CARGO_PKG_VERSION"),
            option_env!("BUILD_SHA")
                .or(option_env!("GITHUB_SHA"))
                .unwrap_or("dev")
        )
    }

    async fn boot(mode: StartMode, environment: &Environment) -> Result<BootResult> {
        create_app::<Self>(mode, environment).await
    }

    fn routes(ctx: &AppContext) -> AppRoutes {
        AppRoutes::empty()
            .prefix("/api")
            .add_app_channels(Self::register_channels(ctx))
    }

    fn register_channels(_ctx: &AppContext) -> AppChannels {
        let messages = channels::state::MessageStore::default();

        let channels: AppChannels = AppChannels::builder().with_state(messages).into();
        channels.register.ns("/", channels::application::on_connect);
        channels
    }

    async fn connect_workers(ctx: &AppContext, queue: &Queue) -> Result<()> {
        Ok(())
    }

    fn register_tasks(_tasks: &mut Tasks) {}
}
```

* Update the `src/bin/main.rs`:

```rs
use loco_rs::cli;
use chat_rooms::app::App;

#[tokio::main]
async fn main() -> loco_rs::Result<()> {
    cli::main::<App>().await
}
```

* Update the `src/channels/state.rs` by adding this `Clone` implementation:

```rs
impl Clone for MessageStore {
    fn clone(&self) -> Self {
        let messages = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap().block_on(async {
            self.messages.read().await.clone()
        });
        MessageStore {
            messages: RwLock::new(messages),
        }
    }
}
```

**Expected Behavior**

The messages aren't transmitted through websocket as the frontend can't connect to the backend anymore.

It seems that some url parameters have been added to the uri path when looking at the logs

```
2024-10-22T08:02:55.818183Z DEBUG http-request: tower_http::trace::on_response: finished processing request 
latency=0 ms status=404 http.method=GET http.uri=/socket.io/?EIO=4&transport=polling&t=PApG1h6 
http.version=HTTP/1.1 http.user_agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like
 Gecko) Chrome/128.0.0.0 Safari/537.36 environment=development request_id=402c7c43-42ee-4441-979c-86ef1c1966d4
```

I'm not sure how we could update the backend to accept the connection and allow this: `http.uri=/socket.io/?EIO=4&transport=polling&t=PApG1h6`

**Comment by chainyo** [comment]
Ok this was coming from the way I used the `socket.io-client` package to connect to the server, I needed to add a `path` option. This was so simple, I spent so much time trying to fix the server ahah.

```ts
socket = io('http://localhost:5150', { path: '/' });
```

**Comment by Sillyvan** [comment]
+1 Something about the routing seems broken here.

Really just seems like Axum didnt register that /socket.io/ path and just returns the fallback which of course leads to an error.

**Comment by ShaneM123** [comment]
Any Update or workaround on this? I'm hoping to use channels

**Comment by Sillyvan** [comment]
Sorry for tagging again @kaplanelad @jondot but can we get some info about this?
I have seen a few people on discord asking about this as well. just making sure it didn't go under the radar

**Comment by kaplanelad** [comment]
Hey @Sillyvan, 
I'm will investigate this issue for the next release

**Comment by kaplanelad** [comment]
After reviewing our implementation of `socketioxide` within the Loco.rs framework, we've decided to remove support for channels.

You can see a working example of char-room  implementation based on `loco` and `socketioxide` with initializer here: https://github.com/loco-rs/chat-rooms
