### ISSUE TITLE
Minor documentation discrepencies

### ISSUE THREAD

**Issue by barvazos** [loco-rs/loco#898]
**Description**

In the getting started guide there is a minor typo in the code snippet for the playground example.

`async fn main() -> loco_re::Result<()> {
    let ctx = playground::<App>().await?;

    // add this:
    let active_model: articles::ActiveModel = articles::ActiveModel {
        title: Set(Some("how to build apps in 3 steps".to_string())),
        content: Set(Some("use Loco: https://loco.rs".to_string())),
        ..Default::default()
    };
    active_model.insert(&ctx.db).await.unwrap();

    let res = articles::Entity::find().all(&ctx.db).await.unwrap();
    println!("{:?}", res);

    Ok(())
}`

Return type shoule be `loco_rs::Result<()>`
(Minor issue as mentioned... Thanks!)

**Comment by barvazos** [comment]
I have noticed another couple of minor issues with the user_report example in the guide:

```
use loco_rs::prelude::*;
use loco_rs::task::Vars;

use crate::models::users;

#[async_trait]
impl Task for UserReport {
    fn task(&self) -> TaskInfo {
      // description that appears on the CLI
        TaskInfo {
            name: "user_report".to_string(),
            detail: "output a user report".to_string(),
        }
    }
```

    // variables through the CLI:
    // $ cargo loco task name:foobar count:2
    // will appear as {"name":"foobar", "count":2} in vars
    async fn run(&self, app_context: &AppContext, vars: &BTreeMap<String, String>) -> Result<()> {
        let users = users::Entity::find().all(&app_context.db).await?;
        println!("args: {vars:?}");
        println!("!!! user_report: listing users !!!");
        println!("------------------------");
        for user in &users {
            println!("user: {}", user.email);
        }
        println!("done: {} users", users.len());
        Ok(())
    }
}`

the example above is missing `pub struct UserReport;`
And the function signature is incorrect. the type for the vars variable should be `&Vars` and not `&BTreeMap<String, String>`

**Comment by barvazos** [comment]
I would also add that all generate commands are missing the specifier ('html' 'htmx' or 'api') 
Thank you so much for creating this framework! I hope I am not being to nit picky with my comments

**Comment by jondot** [comment]
Thanks for finding these!
Could you submit a PR with your suggested fixes?

**Comment by barvazos** [comment]
It looks like these were fixed by someone else? I think the issue can be closed now
