### ISSUE TITLE
generator: Incorrect Mapping for Boolean Fields

### ISSUE THREAD

**Issue by arferreira** [loco-rs/loco#90]
**Description**

Hey folks, the scaffold generation process is causing unexpected behavior when creating controllers with boolean fields. Specifically, the generated code assigns boolean fields as Option<boolean> instead of the correct Option<bool>.

**To Reproduce**

Command:

cargo loco generate scaffold profiles user:references is_doctor:bool! is_patient:bool! is_admin:bool! is_staff:bool! is_psychologist:bo
ol! profile_picture:string address_line_1:string address_line_2:string city:string state:string zip_code:string phone_number:string

**Unexpected Behavior**

The generated controller code includes the following incorrect mappings:

```
    pub is_doctor: Option<boolean>,
    pub is_patient: Option<boolean>,
    pub is_admin: Option<boolean>,
    pub is_staff: Option<boolean>,
    pub is_psychologist: Option<boolean>,
```

**Investigation**

Upon reviewing the code, the issue seems to stem from an incorrect mapping in the PARAMS_MAPPING static hashmap. The boolean type is currently mapped to Option<boolean> instead of the correct Option<bool>.

```
lazy_static! {
    static ref PARAMS_MAPPING: HashMap<&'static str, &'static str> = HashMap::from([
        ("text", "Option<String>"),
        ("string", "Option<String>"),
        ("string!", "Option<String>"),
        ("string^", "Option<String>"),
        ("int", "Option<i32>"),
        ("int!", "Option<i32>"),
        ("int^", "Option<i32>"),
        ("bool", "Option<boolean>"),
        ("bool!", "Option<boolean>"),
        ("ts", "Option<DateTime>"),
        ("ts!", "Option<DateTime>"),
        ("uuid", "Option<Uuid>"),
    ]);
}
```

Should I solve this and submit a PR?

**Comment by jondot** [comment]
Thanks!
Fixed on master.
We'll release a new version later today
