### ISSUE TITLE
Flag to specify configuration directory

### ISSUE THREAD

**Issue by mccormickt** [loco-rs/loco#932]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The default configuration dir of `config` (relative to the application binary) is not configurable. In the case the config dir is mounted at a separate directory or filesystem (e.g. secret volumes, configmaps, etc.) you would have to mount the config file next to the binary in all cases which isn't always easy or possible depending on your deployment pattern.

**Describe the solution you'd like**

An optional command line flag, `-c, --config-dir <CONFIG_DIR>`,  for specifying the configuration directory to read the `<environment>.yaml` file from. It can use the existing [`Config::load_from_folder`](https://github.com/loco-rs/loco/blob/550dc6dab5010c641b22e67ae4e3e13d4f4238e0/src/environment.rs#L71) function, falling back to the default if the flag is not provided. 

**Describe alternatives you've considered**

Mounting configs in the `/usr/bin/` or other application/binary directories which is cumbersome and could unintentionally overwrite existing files.

**Comment by kaplanelad** [comment]
Currently support only environment variable
