### ISSUE TITLE
an error occurs after typing 'App name' 

### ISSUE THREAD

**Issue by Orca-bit** [loco-rs/loco#94]
![image](https://github.com/loco-rs/loco/assets/52285880/5293b50b-8aca-4865-ab9b-12520a70482c)

A timeout occur

**Comment by kaplanelad** [comment]
Hi @Orca-bit,

Please ensure that the application name is in English. The application name is also used as the name of the rust in Cargo.toml, and it should be in English as well.

**Comment by kaplanelad** [comment]
Can you please run with `RUST_LOG=true` and share the results?

**Comment by kaplanelad** [comment]
As there hasn't been any response and the issue appears to be similar to others, I'm closing this matter. Feel free to track the progress on issue #137.

Thank you.
