### ISSUE TITLE
Curl and reqwest nothing response

### ISSUE THREAD

**Issue by aqrun** [loco-rs/loco#961]
**Description**

Curl from cli and reqwest client with 

http://localhost:5150/_ping

nothing response.

But Chrome and postman is ok;

Are there some special settings?

OS: MacOS 14.6.1
loco-rs: { version = "0.12" }
reqwest = { version = "0.12.9" }

**Comment by kaplanelad** [comment]
@aqrun 
I ran a test, and it worked on my end. 
Could you provide additional details to help troubleshoot?

1. Include startup logs from the router endpoints and middlewares. 
2. Share the output of `curl http://localhost:5150/_ping -vvv` for a more detailed view.
3. Confirm if you’re seeing any logs on the server side when executing the curl request.

**Comment by aqrun** [comment]
@kaplanelad very thanks.

1.startup logs:

<img width="1719" alt="image" src="https://github.com/user-attachments/assets/2dd3ef10-86ec-4954-98d1-ab1311e6d8e4">
<img width="1746" alt="image" src="https://github.com/user-attachments/assets/b7c04c17-0784-4022-9d60-06038078eea8">

last 4 debug are from Chrome, is ok:
<img width="1368" alt="image" src="https://github.com/user-attachments/assets/3a036647-c7be-4e0c-b64b-73cd9de5b04e">
2. curl -vvv:
<img width="588" alt="image" src="https://github.com/user-attachments/assets/70f8f72a-c027-4320-a71a-e9b2f18a943c">
3.curl request server side nothing happened
4.direct start axum server is ok:

```rust
let app = Router::new()
    .route("/", get(index))
    .route("/", post(post_index));
let listener = tokio::net::TcpListener::bind("127.0.0.1:3002").await.unwrap();
axum::serve(listener, app).await.unwrap();

async fn post_index() -> Json<Value> {
    Json(json!({
        "name": "alex",
    }))
}
```

<img width="594" alt="image" src="https://github.com/user-attachments/assets/c0035907-5fed-4294-9fbe-0e9b49a38869">

**Comment by aqrun** [comment]
sorry my fault

delete the proxy variables curl works

``
unset https_proxy http_proxy all_proxy
```
