### ISSUE TITLE
Issue with Quick Start Process After Executing loco new

### ISSUE THREAD

**Issue by 0x9bb1** [loco-rs/loco#97]
**Description**

Amazing project, it has been immensely beneficial to me. However, I encountered a problem while following the Quick Start guide. After executing `loco new` and entering the app name, the process stalls and I am unable to proceed further. Any assistance on this matter would be greatly appreciated.

**To Reproduce**

```shell
cargo install loco-cli
```
```
loco new
```

**Expected Behavior**

**Environment:**
`Linux 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
`rustc 1.74.0 (79e9716c9 2023-11-13)`

**Additional Context**
```shell
xxx:/mnt/e/code$ loco new
✔ ❯ App name? · loco_app
^C
```

**Comment by arferreira** [comment]
Hi @0x9bb1, what was the error you find? Seems like you pressed ctrl + c to stop the process, the creation sometimes spend an enough time.

**Comment by 0x9bb1** [comment]
> Hi @0x9bb1, what was the error you find? Seems like you pressed ctrl + c to stop the process, the creation sometimes spend an enough time.

Thank you for the prompt response. I waited for about ten minutes or so. I will retry the process and wait a bit longer to see what happens.

**Comment by 0x9bb1** [comment]
After waiting for a sufficient amount of time, I encountered the error `🙀 SSL error: received early EOF; class=Ssl (16); code=Eof (-20)`. It appears to be caused by an issue with my network. I plan to configure a network proxy and then retry the process. Thank you once again for your assistance.
