### ISSUE TITLE
loco new lets users generate projects with hyphens in their name

### ISSUE THREAD

**Issue by Leikoe** [loco-rs/loco#970]
**Description**

when running `loco new`, there is no validation for special chars in the project name.

**To Reproduce**

```sh
loco new # project name: hello-world
cargo loco start # will fail
```

**Expected Behavior**

validate project names in the loco new command for "-" and fail if it's present.

**Comment by danielsan** [comment]
I think it should just follow Rust's ecosystem's default behavior, which is replacing the dash with an underscore for the logical names, but it could still create the project directory with the dash.

Stopping people from using a dash in 2024 seems more like one of those annoying things that would add to the list of annoyances to those starting to use a new tool. Which eventually can make or break adoption.

**Comment by Leikoe** [comment]
> I think it should just follow Rust's ecosystem's default behavior, which is replacing the dash with an underscore for the logical names, but it could still create the project directory with the dash.
> 
> 
> 
> Stopping people from using a dash in 2024 seems more like one of those annoying things that would add to the list of annoyances to those starting to use a new tool. Which eventually can make or break adoption.

There cannot be a dash in a rust use directive.
Thus failing to compile the base project generated by loco. I do not think this is intended behavior, did you try my commands before answering ?

**Comment by setoelkahfi** [comment]
I just stumbled upon this now. It should just silently convert the project name to the snake-case Rust nomenclature.

**Comment by kaplanelad** [comment]
Resolved with the updated template engine.
To update the loco binary, run:
```
cargo install loco
```
