### ISSUE TITLE
Generate Task potentially places new task registration before curly brace of register_tasks

### ISSUE THREAD

**Issue by Daniel-A-Gutierrez** [loco-rs/loco#986]
**Description**

**To Reproduce**

if src/app.rs -> register_tasks tasks looks like this : 
```
fn register_tasks(tasks: &mut Tasks) 
{
    tasks.register(tasks::seed::SeedData);
}
```

then `cargo loco generate task user_report` will inject the new line above the curly brace like so

```
fn register_tasks(tasks: &mut Tasks)
    tasks.register(tasks::user_report::UserReport);
{
    tasks.register(tasks::seed::SeedData);
}
```

**Expected Behavior**

it should look like 

```
    fn register_tasks(tasks: &mut Tasks)
    {
        tasks.register(tasks::user_report::UserReport);
        tasks.register(tasks::seed::SeedData);
    }
```

**Environment:**
linux x86, working through the tutorial in the getting started guide. 
 
**Additional Context**
I used a customized rustfmt that puts braces on the next line so app.rs was reformatted.

**Comment by jondot** [comment]
resolved in #1012
